### ISSUE TITLE
Barra menu contenente Log in

### ISSUE THREAD

**Issue by renato12** [PorteAperteSulWeb/pasw2015#101]
Vorrei aggiungere/modificare qualche voce sulla barra dei menu situata in alto a destra (per capirci, quella contenente Contatti/Accessibilità/Glossario). E' complicato per chi non conosce php?
Grazie sempre per l'aiuto
Renato

**Comment by cghellere** [comment]
se non ho sbagliato a capire è sufficiente modificare il menù, vai nel pannello admin -> aspetto -> menu -> vai sulla voce  Seleziona un menu da modificare e seleziona Menù superiore, da li puoi togliere/aggiungere/moficare

**Comment by renato12** [comment]
Si, hai ragione in merito al log in, mi ero accorto tardi dell'errore e pensavo di aver modificato anche il titolo oltre al contenuto del messaggio. Il fatto è che sul nostro sito ho spostato il log in sulla barra superiore e la cosa mi ha indotto a dare per scontato che fosse sempre così. 
Grazie mille e scusami per la domanda forse un po' banale. Mea culpa: scambiavo la barra superiore con quella principale.
