### ISSUE TITLE
Messaggi di errore dopo importazione file .xml

### ISSUE THREAD

**Issue by raffaellamura** [PorteAperteSulWeb/pasw2015#117]
Buongiorno,
per l'installazione di pasw2015, ho seguito scrupolosamente la guida e il video da voi preparato.
Dopo l'importazione del file "modello-sito.2014-11-07.xml", ho cliccato su SUBMIT nella schermata "Assign Authors" - "Import attachments" e ho ricevuto dei messaggi di errore:
Failed to import Media “puzzle”
Failed to import Media “team”
Failed to import Media “POF”
Failed to import Media “organizzazione-strutture”
Failed to import Media “calendario”
Failed to import Media “segreteria”
Failed to import Media “stretta-di-mano”
Failed to import Media “iscrizioni”
Failed to import Media “Libri_di_testo”
Failed to import Media “modulistica”
Failed to import Media “segreteria”
Failed to import Media “alla-lavagna”
Failed to import Media “Logo_UST”
Failed to import Media “logo dirigente”
Failed to import Media “logo-regolamento”
Failed to import Media “logo-organigramma”
Failed to import Media “sitemap_icon”
Failed to import Media “icona-crediti”
Failed to import Media “Logo_calendario”
Failed to import Media “icona-pagamenti”
Failed to import Media “immagine-progetti”
Failed to import Media “logo-toolbox”
Failed to import Media “orologio”
Failed to import Media “Il file del tema (SchoolBell)”
Failed to import Media “Il file di importazione del sito”
Il programma mi ha comunque augurato "Have Fun!" e mi ha fatto andare avanti.
Mancano comunque alcune cose nel sito.
Qualche consiglio???
Grazie, Raffaella

**Comment by costanzosanna** [comment]
Stesso problema anche per me. Tu hai risolto? Se sì in che modo?

**Comment by cghellere** [comment]
Il modello fa riferimento a delle immagini che non sono più disponibili e pertanto quell'errore di import. a livello pratico il modello è installato ma in alcune pagine mancano le immagini che la nostra @renatadurighello aveva inserito nel modello, nulla di grave. Puoi cancellare i riferimenti all'inteno delle pagine e inserire immagini tutte tue.

**Comment by costanzosanna** [comment]
Io ora sto procedendo con la creazione del nuovo sito e, in un secondo momento, inserirò le immagini.
