### ISSUE TITLE
errori da console Firefox

### ISSUE THREAD

**Issue by venerdi2** [PorteAperteSulWeb/pasw2015#131]
Nel foglio di stile style.css c'è:
p.pasw2015cookies-banner-text {
    display: inline-block;
    font-size: 10 px;
    line-height: 1 em;
    padding: 0 10px 10px 0;
    position: relative;
}

Credo debba essere:
p.pasw2015cookies-banner-text {
    display: inline-block;
    font-size: 10px;
    line-height: 1em;
    padding: 0 10px 10px 0;
    position: relative;
}
Inoltre in:
.imglinks img:hover {
-webkit-filter: grayscale(0%);
-moz-filter: grayscale(0%);
filter: grayscale(0%);
}
la linea "-moz-filter: grayscale(0%);" dà errore perchè credo non sia più necessaria in quanto firefox accetta la voce "filter"

Saluti

**Comment by cghellere** [comment]
Grazie per la segnalazione.
Ho commentato la parte di codice segnalato in pasw2015cookies-banner-text, dopo una verifica ho verificato che un 10px era troppo piccolo e quindi ho optato per mantenere la dimensione del sito

Marco ha rimosso il codice -moz-filter.
