### ISSUE TITLE
togliere campo ricerca dalla barra menù

### ISSUE THREAD

**Issue by annamundi** [PorteAperteSulWeb/pasw2015#134]
Buongiorno a tutti, vorrei cancellare il campo ricerca dal menù orizzontale per poi inserirlo in altro posto tramite widget; ho provato diverse opzioni che avevo trovato cercando nel web, ma non ci sono riuscita.
Qualcuno mi suggerisce come fare?
Grazie!

**Comment by cghellere** [comment]
Ciao 
se utilizzi un tema child prova ad inserire questo codice nel style.css
.topsearch-div {
display:none !important;
}

se non utilizzi il tema child ricerca nel file style.css questa stringa .topsearch-div { vai a capo ed aggiungi

 display:none;

devi ricordarti che la modifica del file style.css del tema padre verrà cancellata ad ogni aggiornamento.

**Comment by annamundi** [comment]
Ciao
Sì, utilizzo un tema child. 
Inserito, funziona!! Semplice :)
Grazie mille
