### ISSUE TITLE
Il widget albo pretorio non visualizza l'atto

### ISSUE THREAD

**Issue by fast4x** [PorteAperteSulWeb/pasw2015#135]
Utilizzando il widget pasw albo pretorio, cliccando sul link dell'atto che viene proposto, non viene visualizzato nessun atto malgrado nelle impostazioni dello stesso sia presente la pagina dell'albo pretorio.
Ho notato che non viene visualizzato perchè il link all'atto che costruisce il widget è privo della sezione in cui è pubblicato l'atto.
Vale a dire che se l'atto proposto dal widget si trova in www....../albo-pretorio/bandi-di-gara/atto.... il widget lo riscrive in www....../albo-pretorio/atto.... non rimandando all'url corretto.

**Comment by milesimarco** [comment]
Ciao,
ti invito a scrivere a Ignazio Scimone, autore del plugin, così che possa verificare il problema.

**Comment by robert145** [comment]
Ciao,
Scusate se mi intrometto: io  ho risolto creando una pagina chiamata Albo Pretorio ed inserendo lo shortcode: [Albo stato="1" per_page="30"]   (per gli atti correnti). Poi  configurando correttamente il widget, tutto funziona.

**Comment by rinorusso** [comment]
Risolto, la pagina albo pretorio deve obbligatoriamente contenere lo shortcode indicato da Robert mentre nella mia installazione la pagina principale di albo pretorio conteneva i link alle varie categorie di atti.
Adesso l'atto viene visualizzato anche dal widjet....
