### ISSUE TITLE
Problema widget PASW@categorie

### ISSUE THREAD

**Issue by Cate55** [PorteAperteSulWeb/pasw2015#143]
Ciao a tutti, su una nuova installazione non riesco a visualizzare nel widget l'elenco delle categorie da associare (categorie: campo vuoto). Ho importato anche il modello.xml di Renata, ho aggiornato alla versione master, ho rifatto l'installazione ma non riesco proprio a risolvere. Prima volta che mi capita! Grazie per un vostro prezioso aiuto.
link al sito:
http://www.istitutocomprensivojerzu.gov.it/

**Comment by cghellere** [comment]
Ciao Cate
se non ricordo male deve esserci almeno un articolo sulla categoria prima che compaia nella lista, se è vuota non mi pare compaia.

Prova a verificare, crea un articolo anche di test e associalo ad una categoria e poi vedi se questa compare nell'elenco.

Buona giornata

**Comment by Cate55** [comment]
Christian grazieeee infinite ...ho sempre migrato da 2013 a 2015 senza essermi accorta di questo, sono tristemente "testona" :-)
Buona giornata a te!
