### ISSUE TITLE
menù fisso

### ISSUE THREAD

**Issue by camaran** [PorteAperteSulWeb/pasw2015#153]
Andrebbe trovato il modo di includere il codice jquery del menù fisso utilizzando le api di wordpress, ora si include lo script jquery e finsice per farlo più volte

**Comment by camaran** [comment]
parlo di questo pezzo di codice 
<?php if (get_option('pasw_fixedmenu') == 1) { ?>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script>
    jQuery("document").ready(function($){
    var nav = $('#topbar');
    var width = (window.innerWidth > 0) ? window.innerWidth : screen.width;
    $(window).scroll(function () {
        if ($(this).scrollTop() > <?php echo get_custom_header()->height + 30; ?> && width >= 1024) {
            nav.addClass("f-nav");
        } else {
            nav.removeClass("f-nav");
        }
    });
});
</script>

**Comment by milesimarco** [comment]
Si... Ci sono alcune cose che andrebbero ritoccate per sfruttare meglio le api di WP. Questa è una di queste  e la sistemeremo ;)
