### ISSUE TITLE
Come visualizzare un atto scaduto con Albo Pretorio?

### ISSUE THREAD

**Issue by robert145** [PorteAperteSulWeb/pasw2015#154]
Buongiorno,
volevo chiedere come far visualizzare in una pagina (Atti Scaduti), tutti gli atti che appunto non sono più in validità.

Grazie per il lavoro meraviglioso che state facento.

Robert De Carli

**Comment by cghellere** [comment]
Ciao
ricordo che questo spazio è dedicato al tema pasw2015 e non per i setting dei plugin.

se usi il plugin di ignazio devi creare una pagina con il seguente shortcode
[Albo stato="2" filtri="si" minfiltri="no"]
questa è la guida all'uso del plugin http://www.sisviluppo.info/?p=29#shortcode
