### ISSUE TITLE
Pasw2015, uso dei Child Theme: Creare una nuova area "In evidenza" nella Home page

### ISSUE THREAD

**Issue by schiavifabrizio** [PorteAperteSulWeb/pasw2015#155]
Gestisco un sito con il tema pasw2015 ed ho creato un child teme per apportare personalizzazioni ai css ed altro.
ho provato a modificare il footer.php, lo copio nella cartella pasw2015-child...  e va bene!!
ora, sulla home page, voglio creare una nuova area chiamandola "in evidenza" (per il momento statica) immediatamente sopra la sezione sotto-home, ed ho modificato il file home_widgets.php. fatto e testato, provvedo a copiarlo nella cartella pasw2015-child ..... e questo NON va bene!!
praticamente è come se non lo vedesse eseguendo l'originale all'interno della cartella padre pasw2015.
Il mio scopo è quello di creare una nuova area widget sopra la sotto-home ove poter inserire widget o semplice testo html.

Qualcuno sa darmi qualche indicazione per risolvere il problema?

di seguito il codice modificato di home-widgets.php

    <?php $sidebars_widgets = wp_get_sidebars_widgets();

        $i1=0; $i2=0;
        if ( is_active_sidebar('sidebar-3') ) { $i1++; }
        if ( is_active_sidebar('sidebar-4') ) { $i1++; }
        if ( is_active_sidebar('sidebar-5') ) { $i1++; }

        switch ($i1) {
        case 0:
            $width_sottohome = '0%';
            break;
        case 1:
            $width_sottohome = '98%';
            break;
        case 2:
            $width_sottohome = '47%';
            break;
        case 3:
            $width_sottohome = '30%';
            break;
        }

        if ( is_active_sidebar('sidebar-6') ) { $i2++; }
        if ( is_active_sidebar('sidebar-7') ) { $i2++; }
        if ( is_active_sidebar('sidebar-8') ) { $i2++; }

        switch ($i2) {
        case 0:
            $width_home = '0%';
            break;
        case 1:
            $width_home = '98%';
            break;
        case 2:
            $width_home = '47%';
            break;
        case 3:
            $width_home = '30%';
            break;
        }

    ?>

<div class="stickyc">
        <?php if (is_active_sidebar('sidebar-6')) { ?>
            <div class="stickyc-col" style="width: <?php echo $width_home; if ($i2 > 1) { echo '; border-right: 1px dotted #25385D'; } ?>;">
                <ul>
                    <?php dynamic_sidebar("sidebar-6"); ?>
                </ul>
            </div>
        <?php } ?>

        <?php if (is_active_sidebar('sidebar-7')) { ?>
            <div class="stickyc-col" style="width: <?php echo $width_home; if ($i2 == 3) { echo '; border-right: 1px dotted #25385D'; } ?>;">
                <ul>
                    <?php dynamic_sidebar("sidebar-7"); ?>
                </ul>
            </div>
        <?php } ?>

        <?php if (is_active_sidebar('sidebar-8')) { ?>
            <div class="stickyc-col" style="width: <?php echo $width_home;?>;">
                <ul>
                    <?php dynamic_sidebar("sidebar-8"); ?>
                </ul>
            </div>
        <?php } ?>
        <div class="clear"></div>
    </div>

<div id="evidenza-hp">
   <div class="col-com-ev" style="width: <?php echo $width_sottohome;?>;">
	<h2 class="widgettitle">In evidenza</h2>

	<div id="box">
	<img src="........." width="98%" >
	</div>

	<div id="box">
	<img src= "........" width="98%">
	</div>

        <div class="clear"></div>
   </div>
</div>

<div id="sotto-hp">

        <?php if (is_active_sidebar('sidebar-3')) { ?>
            <div class="col-com2" style="width: <?php echo $width_sottohome;?>;">
                <ul>
                    <?php dynamic_sidebar("sidebar-3"); ?>
                </ul>
            </div>
        <?php } ?>

        <?php if (is_active_sidebar('sidebar-4')) { ?>
            <div class="col-com2" style="width: <?php echo $width_sottohome;?>;">
                <ul>
                    <?php dynamic_sidebar("sidebar-4"); ?>
                </ul>
            </div>
        <?php } ?>

        <?php if (is_active_sidebar('sidebar-5')) { ?>
            <div class="col-com2" style="width: <?php echo $width_sottohome;?>;">
                <ul>
                    <?php dynamic_sidebar("sidebar-5"); ?>
                </ul>
            </div>
        <?php } ?>

</div>

**Comment by milesimarco** [comment]
Come mai non compili direttamente il contenuto della homepage?

**Comment by schiavifabrizio** [comment]
Grazie della sollecita risposta.
Ho letto già la sezione di gestione della home page.
praticamente ho impostato:
- la prima fascia con due colonne (news, ultimi atti, circolari, trasparenza) 
- la terza fascia con una unica colonna per gli rss ed uno smootslider iniziale che visualizza i percorsi di studio.
tra queste due fasce mi interessa avere un'area per inserire quattro quadranti con immagini linkabili per attività a cui l'istituto partecipa ponendoli in evidenza: pagine di progetti, orientamento, certificazioni etc.  
per questo chiedevo: come mai per il file "footer.php" il child theme funziona mentre per altri file php no? (es. home-widgets.php).
Grazie
Fabrizio

**Comment by milesimarco** [comment]
Footer.php funziona perché rispetta la "logica" nativa di WordPress (in pratica è un file di struttura previsto di default).

Prova a fare il child per il file index.php e home-widgets.php. Poi puoi modificare :)

Tieni presente che potresti anche creare una fascia statica anziché dinamica (cos'ì ti eviti di perdere tempo con widget e sidebar)

**Comment by milesimarco** [comment]
Chiedo venia, ricordavo male la struttura del tema.

I file sono tmpl_home.php e home-widgets.php (non index.php).

**Comment by schiavifabrizio** [comment]
ho provato a copiare i files (tale e quale) index.php e tmpl_home.php oltre che home-widgets.php modificato come detto. ... non succede nulla. E' come se non vengono ne rilevati e ne letti.

Comunqe l'intenzione è quella di creare una fascia statica come primo step. e se non riesco a risolvere questo quesito, metterò tutto nel tema padre facendo attenzione agli aggiornamenti.

Fabrizio

**Comment by milesimarco** [comment]
Nella cartella del child rinomina il file tmpl_home.php in tmpl_home2.php e nel file modifica "Template Name: Home page" in "Template Name: Home page 2".

Poi apri la homepage in modifica e assegni il nuovo template "Home page 2" anziché "Home page"

**Comment by schiavifabrizio** [comment]
Ho fatto secondo questa prcedura:
1) ho copiato dalla cartella padre pasw2015 nella cartella pasw2015-child il file  tmpl_home.php e rinominato in  tmpl_home2.php; (il file 
2) nel file  tmpl_home2.php in pasw2015-child ho cambiato il parametro(riga 3): "Template Name: Home page 2" 
3) mi sono loggato in wordpress e nella pagina "Home" ho modificato il template con il nuovo "Home page 2" (che viene visualizzato in elenco).

Risultato: nulla come sopra. non viene letto.

ho provato poi a modificare la riga 15 di "tmpl_home2.php" in questo modo:
<?php include(TEMPLATEPATH . '/home-widgets2.php'); ?>
dove "home-widgets2.php" è sempre un file php copia di "home-widgets.php" in pasw2015-child.

Risultato: errore, 2 warnings
Warning: include(C:\wamp\www\pasw/wp-content/themes/pasw2015/home-widgets2.php): failed to open stream: No such file or directory in C:\wamp\www\pasw\wp-content\themes\pasw2015-child\tmpl_home2.php on line 15

Warning: include(): Failed opening 'C:\wamp\www\pasw/wp-content/themes/pasw2015/home-widgets2.php' for inclusion (include_path='.;C:\php\pear') in C:\wamp\www\pasw\wp-content\themes\pasw2015-child\tmpl_home2.php on line 15

Qui http://www.itcgap.com/wp/ puoi vedere il risultato che voglio ottenere.
Saluti
Fabrizio

**Comment by milesimarco** [comment]
Prova <?php include( get_stylesheet_directory() . 'home-widgets2.php' ); ?>

TEMPLATEPATH ritorna il percorso del tema padre, quindi non trova il file.

**Comment by schiavifabrizio** [comment]
Grandeeee!!!
Sembrerebbe funzionare sul mio PC con server wamp!!
faccio i dovuti aggiustamenti e test, poi porto tutto sul sito ufficiale, dopodiché posterò la soluzione definitiva in calce a questa discussione.

**Comment by schiavifabrizio** [comment]
RISOLTO:
Per aggiungere una nuova area statica nella home page:
1) copiare i files PHP home-widgets.php e tmpl_home.php dalla cartella del tema padre pasw2015 nella cartella child pasw2015-child;
2) modificare e aggiungere la nuova area in home-widget.php in pasw2015-child con un blocco note o un qualsiasi IDE;
3) modificare il file tmpl_home.php in pasw2015-child sostituendo la riga di codice PHP: 
<?php include(TEMPLATEPATH . '/home-widgets.php'); ?>
con:
<?php include( get_stylesheet_directory() . '/home-widgets2.php' ); ?>
Fine.

Ringrazio Milesi Marco per il supporto dato per risolvere il problema.

Saluti
Fabrizio
