### ISSUE TITLE
Problema importazione file xml "modello-sito.2014-11-07-corretto.xml" - RISOLTO

### ISSUE THREAD

**Issue by andy650429** [PorteAperteSulWeb/pasw2015#156]
Buongiorno,

Sto installando in locale un sito test (da poi trasferire in "produzione" sul web) un sito wordpress con tema PASW2015. Seguendo le istruzioni relative alla "creazione da zero" ho scaricato anche il file in oggetto (modello-sito.2014-11-07-corretto.xml).

Nell'importazione risulta una serie di errori che elenco...

Failed to import paswdestinatari Alunni
Failed to import paswdestinatari Docenti
Failed to import paswdestinatari Genitori
Failed to import paswdestinatari Personale ATA
Failed to import Media “puzzle”
Failed to import Media “team”
Failed to import Media “POF”
Failed to import Media “organizzazione-strutture”
Failed to import Media “calendario”
Failed to import Media “segreteria”
Failed to import Media “stretta-di-mano”
Failed to import Media “iscrizioni”
Failed to import Media “Libri_di_testo”
Failed to import Media “modulistica”
Failed to import Media “segreteria”
Failed to import Media “alla-lavagna”
Failed to import Media “Logo_UST”
Failed to import Media “logo dirigente”
Failed to import Media “logo-regolamento”
Failed to import Media “logo-organigramma”
Failed to import Media “sitemap_icon”
Failed to import Media “icona-crediti”
Failed to import Media “Logo_calendario”
Failed to import Media “icona-pagamenti”
Failed to import Media “immagine-progetti”
Failed to import Media “logo-toolbox”
Failed to import Media “orologio”
Failed to import Media “Il file del tema (SchoolBell)”
Failed to import Media “Il file di importazione del sito”
Failed to import paswdestinatari Alunni
Failed to import paswdestinatari Genitori
Failed to import paswdestinatari Genitori
Failed to import paswdestinatari Alunni
Failed to import paswdestinatari Docenti
Failed to import paswdestinatari Genitori
Failed to import paswdestinatari Genitori
Failed to import paswdestinatari Docenti
Failed to import paswdestinatari Docenti
Failed to import paswdestinatari Genitori
Failed to import paswdestinatari Docenti
Failed to import paswdestinatari Genitori
Failed to import paswdestinatari Personale ATA
Failed to import paswdestinatari Alunni
Failed to import paswdestinatari Docenti
Failed to import paswdestinatari Genitori
Failed to import paswdestinatari Alunni
Failed to import paswdestinatari Docenti
Failed to import paswdestinatari Genitori
Failed to import paswdestinatari Genitori
Failed to import paswdestinatari Docenti
Failed to import paswdestinatari Personale ATA
Failed to import paswdestinatari Alunni
Failed to import paswdestinatari Docenti
Failed to import paswdestinatari Genitori
Failed to import paswdestinatari Personale ATA
Failed to import paswdestinatari Genitori
Failed to import paswdestinatari Docenti
Failed to import paswdestinatari Alunni
Failed to import paswdestinatari Docenti
Failed to import paswdestinatari Genitori
Failed to import paswdestinatari Alunni
Failed to import paswdestinatari Docenti
Failed to import paswdestinatari Personale ATA

Investigando all'interno del file, vedo che è richiamato un sito che però risulta sostanzialmente vuoto... nel senso che ogni link richiamato nel file xml non porta ad alcun contenuto del sito www.renatadurighello.it

Ma forse questo non è un problema particolare perchè mi pare che le pagine siano comunque state create. L'unica cosa è che se proseguo alla fine la struttura del sito non è funzionante... addirittura le pagine non si visualizzano (errore 404) pur se create e con contenuti.

potete darmi qualche dritta?

Nel frattempo auguro a tutti buon anno e a presto!

Andrea

**Comment by renatadurighello** [comment]
In effetti le immagini non sono più reperibili. Mi riprometto sempre di
creare un nuovo modello, anche perché dall'ultimo aggiornamento di
wordpress ci sono a volte altre imprecisioni nelle pagine destinatari.
Per il problema dell'errore 404 prova ad aggiornare i permalink.

Renata Durighello

su Android
Il 06/gen/2016 11:24 "andy650429" <notifications@github.com> ha scritto:

**Comment by cghellere** [comment]
Ciao
come da te riportato l'errore relativo ai media è legato al fatto che i link non sono più attivi ma questo non comporta problemi bloccanti.
il secondo errore è legato al fatto che prima dell'import del file xml tu con molta probabilità non hai attivato il modulo Destinatari e quindi non risulta possibile creare ed importare i destinatari.

Visto che il tutto è in locale io ti consiglio di ricreare l'ambiente e provare a fare l'import dopo aver attivato il modulo destinatari. Certo questo non risolve il problema delle immagini.

**Comment by andy650429** [comment]
Ciao e intanto grazie!
Testo subito e vi giro il feedback...
a tra poco!

**Comment by andy650429** [comment]
Eccomi qui...

si... con la gestione semplice dei permalink ora funziona correttamente!

Vi ringrazio vivamente per la collaborazione e a presto...
mi metto al lavoro...

Il dominio su cui installerò è "lenoservizi.it"... è una società integralmente pubblica in house providing affidataria diretta di servizi pubblici e credo sia opportuno che vengano utilizzati gli strumenti idonei, visto che tali società sono soggette tanto quanto gli enti locali alle norme relative soprattutto alla trasparenza... 
Già da tempo ho provveduto ad utilizzare il plugin di Marco che permette sia la gestione della trasparenza che dei dati per l'ANAC... e li trovo eccellenti. 
Grazie per il lavoro che fate.

A presto!

Andrea
