### ISSUE TITLE
Problema con Albo Pretorio/PAFacile... sito "bianco"... 

### ISSUE THREAD

**Issue by andy650429** [PorteAperteSulWeb/pasw2015#157]
Ciao a tutti...
ultimo problema... 
installando (in locale) in pasw2015 anche il plugin Albo Pretorio in unione con PAFacile, emerge un errore...
All'attivazione il sito non risponde più... neppure lato amministrazione. Tutto bianco.
In wp_config.php ho attivato il debug e l'errore è il seguente:

Strict Standards: Only variables should be assigned by reference in /var/www/html/wp-content/plugins/albo-pretorio-on-line/AlboPretorio.php on line 76

Fatal error: Cannot redeclare class AlboPretorio in /var/www/html/wp-content/plugins/pafacile/public-contents/AlboPretorio.php on line 23

La prima l'ho risolta... è bastato togliere & nella riga e l'errore è sparito...
il secondo invece non riesco a "sanarlo"... non mi pare proprio che la classe sia chiamata più volte in quella specifica riga (o anche prima...)

Al momento ho disattivato PAFacile e il sito ha ripreso a funzionare... 
se avete idee... grazie e a presto!

Andrea

**Comment by milesimarco** [comment]
Ciao,
tieni presente che il plugin non è realizzato da Porte Aperte sul Web. Il problema è che stai usando due plugin per l'albo che contengono una classe con lo stesso nome.

**Comment by andy650429** [comment]
Ciao Marco!
ok... allora meglio dimenticare PAFacile... tengo solo Albo Pretorio... meglio così...
Intanto grazie e a presto!

Andrea

**Comment by milesimarco** [comment]
Prego! A presto!
