### ISSUE TITLE
Problema con Albo Pretorio - impossibile memorizzare un nuovo atto [risolto]

### ISSUE THREAD

**Issue by andy650429** [PorteAperteSulWeb/pasw2015#158]
Ciao,

in una installazione in locale del plugin sotto pasw2015 non risulta possibile memorizzare un atto: 
pur compilando ogni campo correttamente (incluso l'oggetto) la pagina mi ritorna 

Impossibile memorizzare l'atto:
Bisogna inserire l'Oggetto

Non capisco il motivo... ovviamente ho già creato sia i responsabili che le categorie

Ciao e grazie!

Andrea

**Comment by andy650429** [comment]
Ciao a tutti...
nessuno ha qualche suggerimento sul problema riscontrato?
non riesco a risolvere... non so perchè...

Ciao e ancora grazie

Andrea

**Comment by maupao** [comment]
Il giorno Wed, 06 Jan 2016 05:28:08 -0800
andy650429 <notifications@github.com> ha scritto:

> Impossibile memorizzare l'atto:
> Bisogna inserire l'Oggetto
Presumo che l'oggetto sia stato inserito...

--
Paolo Mauri
Linux User #462825
irc maupao
twitter @mauri_paolo
www.paolomauri.it
google+ https://www.google.com/+PaoloMauri

un sistema libero per la scuola
http://wiildos.wikispaces.com

Esci dall'illegalità: utilizza LibreOffice.org: 
http://www.libreoffice.org/download
http://linguistico.sourceforge.net/wiki/doku.php?id=usaooo
http://linguistico.sourceforge.net/pages/traduzioni/ms_illegal.html

**Comment by andy650429** [comment]
Certamente... è obbligatorio... ma il sistema "torna" con "inserire oggetto"...

**Comment by andy650429** [comment]
ragazzi...mi è venuto un sospetto... ed era giusto... scusate...
Ho installato un plugin "RichTextEditor For WordPress" che mi aiuta nella composizione delle pagine... l'ho disattivato e ora gli atti vengono memorizzati... 
Quindi è un problema di interazione tra quel plugin e quello dell'albo pretorio... 
Mi scuso se non ero riuscito a identificare il problema.

Forse per la prossima edizione del vostro plugin potreste mettere una patch... non so...
Cmq ora so e agisco di conseguenza!

Grazie ancora e a presto!!!

Andrea

**Comment by milesimarco** [comment]
Grazie per il feedback
