### ISSUE TITLE
Problemi importazione

### ISSUE THREAD

**Issue by alespagl** [PorteAperteSulWeb/pasw2015#159]
Provo a fare l'importazione e non mi da tutte le pagine ad esempio la pagina statica home non compare proprio.... così anche diverse immagini mi compare il messaggio Failed

**Comment by cghellere** [comment]
Ciao @alespagl 
le immagini puntano a delle url che non ci sono più, ma questo non comporta alcun problema.
Per la home devi andare tu ad impostare nelle configurazioni di wordpress quale è la home page, pagina di amministrazione -> impostazioni -> lettura  voce La pagina iniziale visualizza:

**Comment by alespagl** [comment]
ok gentilissimo
