### ISSUE TITLE
plugin wp user 

### ISSUE THREAD

**Issue by profagnelotti** [PorteAperteSulWeb/pasw2015#166]
L'attivazione del plugin WP User non cambia la pagina di login
(http://www.agnelotti.it/IVBRIM20152016)

**Comment by cghellere** [comment]
Ciao scusami ho cercato in rete ma con wp user escono molti plugin, potresti riportare il link alla pagina del plugin. Vorrei capire cosa fa quel plugin in quanto non lo conosco

grazie

**Comment by profagnelotti** [comment]
Ciao ti ringrazio per la sollecitudine; il link è https://wordpress.org/plugins/wp-user/. Il plugin dovrebbe aggiungere funzionalità come la registrazione degli utenti etc. L'ho sostituito con "WP User Manager" che, al contrario, funziona. Grazie ancora

**Comment by cghellere** [comment]
Ciao
io ho provato il plung in un sito in locale e funziona, anche se la versione free non puo' sostituire wp user manager al massimo sostituisce Theme My Login.

Una volta attivato il plugin devi creare una nuova pagina e inserire questo shotcode [wp_user], se poi visualizzi la pagina ti compare il modulo di login.

Ciao
