### ISSUE TITLE
Widget PASW @ Categorie - link visualizza tutto

### ISSUE THREAD

**Issue by renatadurighello** [PorteAperteSulWeb/pasw2015#167]
Il link "visualizza tutto" non appare se non si mette un titolo al widget, o almeno è quello che è successo a me: ho inserito un widget di testo con immagine/logo direttamente sopra il widget, evitando il titolo, ma in questo modo non mi appare più il link, che invece a me serve.
ciao Renata

**Comment by cghellere** [comment]
Grazie ora viene visualizzato Tutti gli articoli della categoria XXXXX
