### ISSUE TITLE
Widget Link

### ISSUE THREAD

**Issue by icfermi** [PorteAperteSulWeb/pasw2015#168]
Ho da poco installato il tema Pasw2015 (versione 1.6.6), ma in Aspetto-Widget, non visualizzo il widget Link. Posso farlo comparire in qualche modo?
Grazie.
Christian Silva

**Comment by renatadurighello** [comment]
Non è un problema del tema. Da alcune versioni Wordpress non fornisce più il widget link di default, perché è possibile ottenere lo stesso risultato con un widget di menù personalizzato.
Per funzionalità più sodisticate ci sono soluzioni di ogni tipo nel repository ufficiale dei plugin di wordpress.
