### ISSUE TITLE
Visualizzazione circolari

### ISSUE THREAD

**Issue by NinoRepaci** [PorteAperteSulWeb/pasw2015#170]
Tema pasw15. Ho installato il plugin circolari gropup e creato i gruppi. Creata la pagina di raccolte circolari con lo shortcode [VisCircolari], inserita la categoria PASW-circolari nella sottohome DX. Ebbene se scrivo le circolari nel plugin circolari, le vedo nella raccolta, ma non nella home. Se scrivo la circolare come post (articolo), allora è presente in entrambi i posti. Chi mi risolve il problema? E soprattutto in circolari--parametri, gruppo pubblico Tutti..ma come categoria? Io ne ho creata una chiamata Comunicazioni, ma non c'è nessuna pagina associata ad essa. Grazie.

**Comment by cghellere** [comment]
Ciao ora non ho visionato il codice del widget pasw-circolari e non ho il plugin circolari group per fare eventualmente dei test, per raggirare il problema se non erro la versione di Ignazio ha anche un suo widget prova ad utilizzare quello.

**Comment by maupao** [comment]
Il giorno Thu, 16 Jun 2016 09:28:37 -0700
NinoRepaci <notifications@github.com> ha scritto:

> Tema pasw15. Ho installato il plugin circolari gropup e creato i
> gruppi. Creata la pagina di raccolte circolari con lo shortcode
> [VisCircolari], inserita la categoria PASW-circolari nella sottohome
> DX. Ebbene se scrivo le circolari nel plugin circolari, le vedo nella
> raccolta, ma non nella home.
ciao
Le circolari che vedi nel plugin che metti nella sottohome sono quelle
che hanno la categoria che hai indicato come pubblica nelle
impostazioni del plugin.
> Se scrivo la circolare come post
> (articolo), allora è presente in entrambi i posti. Chi mi risolve il
> problema? E soprattutto in circolari--parametri, gruppo pubblico
> Tutti..ma come categoria? Io ne ho creata una chiamata Comunicazioni,
> ma non c'è nessuna pagina associata ad essa.
Per far comparire la circolare in home allora devi assegnarla al gruppo
tutti. Le categorie sono riservate agli articoli. Per le circolari con
il plugin di Ignazio viene gestito tutto dai gruppi.
Spero di essere riuscito a spiegarmi.

--
Paolo Mauri
Linux User #462825
irc maupao
twitter @mauri_paolo
www.paolomauri.it
google+ https://www.google.com/+PaoloMauri

un sistema libero per la scuola
http://sodilinux.itd.cnr.it/

Esci dall'illegalità: utilizza LibreOffice.org: 
http://www.libreoffice.org/download
http://linguistico.sourceforge.net/wiki/doku.php?id=usaooo
http://linguistico.sourceforge.net/pages/traduzioni/ms_illegal.html

**Comment by NinoRepaci** [comment]
Buongiorno,
come scrive maupau, io vedo nella sottohome solo quelle indicate nella categoria pubblica. Il problema era che la categoria pubblica era associata alla parola "tutti". Questo non lo ritengo corretto perchè se la circolare è riferita ai soli docenti, perchè si veda nella sottohome accanto a docenti appare anche "tutti" come se fosse rivolta anche ad altri soggetti. Allora per aggirare il problema mi sono creato un gruppo pubblico con alcune combinazioni di caratteri ascii (alt+255, alt+254) così facendo ottengo un simbolo che non disturba che può accompagnare i destinatari dell'atto. Grazie a tutti per l'aiuto.
