### ISSUE TITLE
Problemi con l'installazione del modello del sito (pasw2015) di Renata Durighello

### ISSUE THREAD

**Issue by costanzosanna** [PorteAperteSulWeb/pasw2015#174]
Salve, 
mi sono dovuto fermare con la creazione di un sito scolastico con il tema pasw2015 in quanto, durante l'importazione del "modello-sito.2014-11-07-corretto" in formato xml di Renata Durighello, con il plugin Importatore Wordpress mi sono apparsi segnali di errore: sono stati importati i 6 articoli e le 45 pagine del modello, ma per altre decine di file, nel report è apparsa la dicitura che non è stato possibile importarli.
Ho provato a importarli di nuovo, ma le pagine del sito sono state duplicate e allora ho dovuto cancellare tutto e iniziare nuovamente con l'installazione da zero.
Spero di poter risolvere il problema caricando il modello in xml anziché tramite Wordpress Importer, via ftp. Però non saprei in quale cartella della memoria del sito installare il modello. Sono autodidatta e nelle istruzioni non è indicato in alcun punto, a differenza del tema.
Grazie a chi vorrà gentilmente darmi una dritta.

**Comment by renatadurighello** [comment]
Ciao, gli errori si riferiscono ad immagini. Fino a qualche tempo fa erano depositate in un mio spazio, ma poi le ho inavvertitamente cancellate senza salvarle. Erano solo immagini decorative, trovate in internet. Non succede niente se non ci sono, solo quando apri una pagina potresti provare il "buco" segnaposto. Sarai tu stesso a scegliere, per la segreteria, il collegio docenti... l'immagine che riterrai più rappresentativa. 
Non caricare invece il file via ftp, non funzionerebbe: il plugin lo installa, andando a modificare il database, il file caricato via ftp starebbe lì staticamente. 
Il modello migliorabile, ma in linea di massima funziona e risparmia un bel po' di lavoro.
buon lavoro,
Renata

**Comment by costanzosanna** [comment]
Ciao, grazie infinite della risposta chiarificatrice. Mi stavo un po' scoraggiando. Ora posso riprendere con entusiasmo.
Finora usavo pasw2013 ed è andato molto bene [www.scuoleorani.it](url). Ora il nostro istituto sta passando al .gov con pasw2015. 
Il tuo modello permette di facilitare notevolmente il lavoro nella fase di realizzazione delle pagine e di realizzare un sito organico ed efficiente; è giusto che ogni scuola scelga le proprie immagini, per evitare l'omologazione.
Il vostro staff è eccezionale!
Visto che siete così bravi, perché non pensate di elaborare anche un modello di registro?
Buone cose
Costanzo

**Comment by renatadurighello** [comment]
Se devi solo passare da pasw 2013 al 2015 puoi evitare di rifare il sito. Così come puoi importare un modello puoi anche esportare il tuo sito (esporta, anziché importa da strumenti di wordpress) e importarlo nel nuovo spazio e poi il passaggio a pasw 2013 non è complicato, anche per quello ci sono dei tutorial on line. Se invece devi fare cambiamenti più pesanti, allora prosegui come stai facnedo.
Ciao Renata

**Comment by costanzosanna** [comment]
Ero indeciso se fare la migrazione, ma molti me l'hanno sconsigliata nel passaggio al .gov e non ho voluto rischiare, perché con pasw2013 ho personalizzato un po' troppo il vostro modello e in Amministrazione trasparente ho  creato manualmente tutte le pagine, pur seguendo il vostro schema. Quindi, avrei dovuto fare un lavoro di adeguamento dopo. 
Ora vorrei restare vicino il più possibile al tuo modello, in modo che non mi salti qualcosa con gli aggiornamenti.
Sto pensando di creare le icone, quando avrò tempo, con la tavoletta grafica (come i miei alunni!).
Se avessi ricevuto prima i tuoi consigli, forse avrei tentato la migrazione.
Certo, non posso inserire vecchie le circolari. Inizierò dal prossimo anno scolastico con le nuove e con il nuovo albo pretorio.
In Amministrazione trasparente, invece, sto pensando di inserire i vecchi documenti.
Ciao e grazie.
Costanzo
