### ISSUE TITLE
Sidebar fantasma

### ISSUE THREAD

**Issue by equinozio63** [PorteAperteSulWeb/pasw2015#177]
Ho attivato dei widget nella sidebar dx e sx ma non compaiono sulla home del sito che, peraltro, appare come "compressa".

**Comment by cghellere** [comment]
salve è possibile avere l'url del sito? ha provato ad inserire il widget ricerca in una delle due barre.

**Comment by equinozio63** [comment]
Certamente.

Widget "ricerca" inserito e compare. Sotto ho inserito calendario e non compare.

Idem sulla barra a sx: inserite diverse cose ma non appare nulla.

La cosa anomala è data dal fatto che, cliccando su Alunni Genitori etc..  si apre il sito regolarmente.

Colpa della copia beta?


Grazie, Christian


Angelo


http://www.scuolebarlassina.gov.it/BetaTest


________________________________
Da: Christian Ghellere <notifications@github.com>
Inviato: venerdì 5 agosto 2016 11.28
A: PorteAperteSulWeb/pasw2015
Cc: equinozio63; Author
Oggetto: Re: [PorteAperteSulWeb/pasw2015] Sidebar fantasma (#177)


salve è possibile avere l'url del sito? ha provato ad inserire il widget ricerca in una delle due barre.

-

**Comment by cghellere** [comment]
Ciao 
alla pagina identificata come home hai assegnato il template home page?

**Comment by equinozio63** [comment]
Sei fantastico.


Grazie.


Non ci sarei mai riuscito senza il tuo aiuto.


Angelo


________________________________
Da: Christian Ghellere <notifications@github.com>
Inviato: martedì 9 agosto 2016 08.26
A: PorteAperteSulWeb/pasw2015
Cc: equinozio63; Author
Oggetto: Re: [PorteAperteSulWeb/pasw2015] Sidebar fantasma (#177)


Ciao
alla pagina identificata come home hai assegnato il template home page?

-
