### ISSUE TITLE
Non si salvano le IMPOSTAZIONI in Pasw2015

### ISSUE THREAD

**Issue by Alexander2020** [PorteAperteSulWeb/pasw2015#179]
Salve, ho installato PASW 2015 su WP 4.6.1
Nel momento in cui vado a inserire le informazioni nella sezione PASW 2015 - IMPOSTAZIONI, qualsiasi campo riempio e poi clicco su SALVA IMPOSTAZIONI, le informazioni non vengono salvate.
Perciò non riesco a mettere i recapiti della scuola nel footer.
Come posso risolvere il problema ? Grazie

**Comment by cghellere** [comment]
Ciao 
è una nuova installazione?
hai plugin installati? se si prova a disabilitarli e provare 
altro passo è quello di disattivare il tema pasw2015, cancellare il tema tramite ftp, ricaricare i file e riattivare il tema.

**Comment by Alexander2020** [comment]
Ho disattivato e reinstallato il tema come mi ha suggerito, ora è tutto ok, grazie gentilissimo
