### ISSUE TITLE
Problemi con PaswCategorie

### ISSUE THREAD

**Issue by toronto2015** [PorteAperteSulWeb/pasw2015#183]
Buongiorno,
pur inserendo il widget nella seconda fascia , in home non mi compare niente.

**Comment by milesimarco** [comment]
Ciao,
hai impostato il template home nella pagina che hai scelto come homepage?

**Comment by toronto2015** [comment]
Fatto! funziona grazie mille.

**Comment by IcCentroStorico** [comment]
E' possibile aumentare in qualche modo il valore massimo degli articoli mostrati dal widget PASWcategorie che ora è limitato a 10?
