### ISSUE TITLE
Problema testo nell'header

### ISSUE THREAD

**Issue by Baldo28** [PorteAperteSulWeb/pasw2015#190]
Buongiorno a tutti; sono Baldo e gestisco il sito dell'IC Casella (GE) [www.iccasella.gov.it](url)
Stamattina sono passato da PASW2013 a 2015; tutto bene salvo che tra i dati dell'istituto nell'header non riesco a far vedere gli indirizzi di posta (invece compaiono regolarmente nel footer) nè comunque a modificare la formattazione.
Ho guardato nelle guide, nei tutorial ed in questo forum ma non ho trovato risposta; ho anche provato ad editare e modificare l'header.php con danni per fortuna rimediati!
Guardando tra vari siti che usano il tema, ho visto soluzioni anche complesse nella formattazione, ma non so come procedere; l'unica idea che mi è venuta è quella di caricare un'immagine con le dimensioni consigliate (1150 x 125 px) contenente il testo come lo gradisco e con lo sfondo trasparente. Mi chiedevo se esiste un'altra soluzione.
Grazie comunque per ogni aiuto!
Marco Baldelli "Baldo"

**Comment by cghellere** [comment]
Ciao questo http://www.icscarpa.gov.it/ è quanto compare con un tema pasw2015 puro, quest'altro http://icbrendola.gov.it/ invece è frutto di un tema child, che puoi scaricare da qui https://github.com/PorteAperteSulWeb/pasw2015-child/tree/Christian. Attenzione il tema child si appoggia al tema padre ti consiglio di leggere le wiki presenti.

Christian

**Comment by Baldo28** [comment]
Grazie Christian. Ho iniziato a leggere le wiki, proseguo e proverò; non mi risulta ancora chiaro cosa non mi funzioni col tema puro.
Baldo
