### ISSUE TITLE
categorie in amministrazione trasparente

### ISSUE THREAD

**Issue by Omeromuscio** [PorteAperteSulWeb/pasw2015#192]
buongiorno a tutti 

mi dicono dall'amministrazioone che in amministrazione traparente dovrebbero esserci altre categorie

nello specifico riporto un paragrafo di un pdf anac 
" Tali dati devono essere inseriti in un apposita sottosezione di Amministrazione trasparente " denomita 
" Pagamenti dell'amministrazione traparente/Dati sui pagamenti"

è possibile inserire queste categorie ?
o credete sia previsto un upgrade del plugin perciò ?

grazie Alberto

**Comment by cghellere** [comment]
Ciao @Omeromuscio 
questo spazio è dedicato al tema pasw2015, per i plugin di @milesimarco ci sono altri posti vedi ad esempio il forum di supporto presente nel suo sito https://wpgov.it/supporto/forum/wordpress-pa/amministrazione-trasparente-wordpress-plugin/

Grazie e buone feste

**Comment by Omeromuscio** [comment]
grazie Cristian !!!
