### ISSUE TITLE
Validazione XML

### ISSUE THREAD

**Issue by icmanincasavio** [PorteAperteSulWeb/pasw2015#196]
Per chi usasse il plugin Bandi di Gara e generasse il dataset XML, in fondo alla pagina è riportato un link con il validatore gratuito online.
Il link non funziona correttamente, occorre digitare il nome di uno dei due siti che forniscono questo servizio.
Io ne ho trovato un altro che può fare al caso: http://www.amministrazionicomunali.it/main/xml_avcp_validator.php
Buon lavoro a tutti

Luciano

**Comment by cghellere** [comment]
Ciao Luciano,
grazie per la segnalazione, ma questo non è il luogo corretto in quanto quest'area è per il tema pasw2015.
Per i plugin Marco mette a disposizione un forum dedicato, per questa tua segnalazione il luogo più corretto è https://wpgov.it/supporto/forum/wordpress-pa/wp-avcp/ .

Grazie e buona giornata

Christian
