### ISSUE TITLE
Riscrivere nome directory

### ISSUE THREAD

**Issue by roberbi** [PorteAperteSulWeb/pasw2015#201]
Con l'ultimo aggiornamento 1.7 in bacheca appare il seguente avviso:
Pasw2015 è installato nella directory "PorteAperteSulWeb-pasw2015-58014d6". Per un corretto funzionamento è necessario cambiare il nome della cartella in "pasw2015".
Questo messaggio scomparirà automaticamente correggendo il problema."

Ho cambiato il nome via ftp ma appena fatto il sito è scomparso, momenti di panico, per fortuna avevo copiato il nome originale, lunghissimo, e rinominato nuovamente la directory e tutto è tornato a posto.

Come si rinomina il nome della directory

**Comment by emitz** [comment]
Ho effettuato l'aggiornamento e si è verificato lo stesso tuo problema. Ho provato, come hai fatti tu, a rinominare la cartella ma anche a me è scomparso il sito e quindi ho rinominato nuovamente. 
Tu sei poi riuscito a risolvere il problema?

**Comment by roberbi** [comment]
CiaoNo. Il problema rimane e ho deciso di lasciarlo cosí. Di tutti i temi che utilizzo e ho provato questo è l'unico che chiede di riscrivere il nome della cartella in cui si installa. Sono contento comunque che dopo alcuni mesi ho un riscontro anche se puttroppo negativo. Speriamo che qualcuno ci dica cosa fare o magari il prossimo aggiornamento risolve. Chissà magari invece scassa tutto e ci tocca cambiare tema. Aggiornami se hai novità.Roberto


Inviato da smartphone Samsung Galaxy.
-------- Messaggio originale --------Da: emitz <notifications@github.com> Data: 11/07/17  17:45  (GMT+01:00) A: PorteAperteSulWeb/pasw2015 <pasw2015@noreply.github.com> Cc: roberbi <rbtbnc@gmail.com>, Author <author@noreply.github.com> Oggetto: Re: [PorteAperteSulWeb/pasw2015] Riscrivere nome directory (#201) 
Ho effettuato l'aggiornamento e si è verificato lo stesso tuo problema. Ho provato, come hai fatti tu, a rinominare la cartella ma anche a me è scomparso il sito e quindi ho rinominato nuovamente.

Tu sei poi riuscito a risolvere il problema?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/PorteAperteSulWeb/pasw2015","title":"PorteAperteSulWeb/pasw2015","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/PorteAperteSulWeb/pasw2015"}},"updates":{"snippets":[{"icon":"PERSON","message":"@emitz in #201: Ho effettuato l'aggiornamento e si è verificato lo stesso tuo problema. Ho provato, come hai fatti tu, a rinominare la cartella ma anche a me è scomparso il sito e quindi ho rinominato nuovamente. \r\nTu sei poi riuscito a risolvere il problema? "}],"action":{"name":"View Issue","url":"https://github.com/PorteAperteSulWeb/pasw2015/issues/201#issuecomment-314486707"}}}

**Comment by emitz** [comment]
Ciao Roberto, ho risolto😄
Ho ricevuto il suggerimento da Ghellere:
Prima devi cambiare tema e poi rinomini la cartella. Ha funzionato!!!
Ciao
Emanuela

martedì 11 luglio 2017, 18:39 +0200 da roberbi  <notifications@github.com>:

**Comment by roberbi** [comment]
CiaoSono contento che ty abbia risolto, ma non capisco cosa significa cambiare tema?Devo installare un altro tema e poi di nuovo pasw15?GrazieRoberto


Inviato da smartphone Samsung Galaxy.
-------- Messaggio originale --------Da: emitz <notifications@github.com> Data: 12/07/17  17:45  (GMT+01:00) A: PorteAperteSulWeb/pasw2015 <pasw2015@noreply.github.com> Cc: roberbi <rbtbnc@gmail.com>, Author <author@noreply.github.com> Oggetto: Re: [PorteAperteSulWeb/pasw2015] Riscrivere nome directory (#201) 


Ciao Roberto, ho risolto😄

Ho ricevuto il suggerimento da Ghellere:

Prima devi cambiare tema e poi rinomini la cartella. Ha funzionato!!!

Ciao

Emanuela



martedì 11 luglio 2017, 18:39 +0200 da roberbi  <notifications@github.com>:

>CiaoNo. Il problema rimane e ho deciso di lasciarlo cosí. Di tutti i temi che utilizzo e ho provato questo è l'unico che chiede di riscrivere il nome della cartella in cui si installa. Sono contento comunque che dopo alcuni mesi ho un riscontro anche se puttroppo negativo. Speriamo che qualcuno ci dica cosa fare o magari il prossimo aggiornamento risolve. Chissà magari invece scassa tutto e ci tocca cambiare tema. Aggiornami se hai novità.Roberto

>

>

>Inviato da smartphone Samsung Galaxy.

>-------- Messaggio originale --------Da: emitz < notifications@github.com > Data: 11/07/17  17:45  (GMT+01:00) A: PorteAperteSulWeb/pasw2015 < pasw2015@noreply.github.com > Cc: roberbi < rbtbnc@gmail.com >, Author < author@noreply.github.com > Oggetto: Re: [PorteAperteSulWeb/pasw2015] Riscrivere nome directory (#201) 

>Ho effettuato l'aggiornamento e si è verificato lo stesso tuo problema. Ho provato, come hai fatti tu, a rinominare la cartella ma anche a me è scomparso il sito e quindi ho rinominato nuovamente.

>

>Tu sei poi riuscito a risolvere il problema?

>

>—

>You are receiving this because you authored the thread.

>Reply to this email directly, view it on GitHub, or mute the thread.

>

>

>

>

>

>

>

>

>{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/PorteAperteSulWeb/pasw2015","title":"PorteAperteSulWeb/pasw2015","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/PorteAperteSulWeb/pasw2015"}},"updates":{"snippets":[{"icon":"PERSON","message":"@emitz in #201: Ho effettuato l'aggiornamento e si è verificato lo stesso tuo problema. Ho provato, come hai fatti tu, a rinominare la cartella ma anche a me è scomparso il sito e quindi ho rinominato nuovamente. \r\nTu sei poi riuscito a risolvere il problema? "}],"action":{"name":"View Issue","url":"https://github.com/PorteAperteSulWeb/pasw2015/issues/201#issuecomment-314486707"}}}

>—

>You are receiving this because you commented.

>Reply to this email directly,  view it on GitHub , or  mute the thread .



—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/PorteAperteSulWeb/pasw2015","title":"PorteAperteSulWeb/pasw2015","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/PorteAperteSulWeb/pasw2015"}},"updates":{"snippets":[{"icon":"PERSON","message":"@emitz in #201: \nCiao Roberto, ho risolto😄\nHo ricevuto il suggerimento da Ghellere:\nPrima devi cambiare tema e poi rinomini la cartella. Ha funzionato!!!\nCiao\nEmanuela\n\nmartedì 11 luglio 2017, 18:39 +0200 da roberbi  \u003cnotifications@github.com\u003e:\n\u003eCiaoNo. Il problema rimane e ho deciso di lasciarlo cosí. Di tutti i temi che utilizzo e ho provato questo è l'unico che chiede di riscrivere il nome della cartella in cui si installa. Sono contento comunque che dopo alcuni mesi ho un riscontro anche se puttroppo negativo. Speriamo che qualcuno ci dica cosa fare o magari il prossimo aggiornamento risolve. Chissà magari invece scassa tutto e ci tocca cambiare tema. Aggiornami se hai novità.Roberto\n\u003e\n\u003e\n\u003eInviato da smartphone Samsung Galaxy.\n\u003e-------- Messaggio originale --------Da: emitz \u003c notifications@github.com \u003e Data: 11/07/17  17:45  (GMT+01:00) A: PorteAperteSulWeb/pasw2015 \u003c pasw2015@noreply.github.com \u003e Cc: roberbi \u003c rbtbnc@gmail.com \u003e, Author \u003c author@noreply.github.com \u003e Oggetto: Re: [PorteAperteSulWeb/pasw2015] Riscrivere nome directory (#201) \n\u003eHo effettuato l'aggiornamento e si è verificato lo stesso tuo problema. Ho provato, come hai fatti tu, a rinominare la cartella ma anche a me è scomparso il sito e quindi ho rinominato nuovamente.\n\u003e\n\u003eTu sei poi riuscito a risolvere il problema?\n\u003e\n\u003e—\n\u003eYou are receiving this because you authored the thread.\n\u003eReply to this email directly, view it on GitHub, or mute the thread.\n\u003e\n\u003e\n\u003e\n\u003e\n\u003e\n\u003e\n\u003e\n\u003e\n\u003e{\"api_version\":\"1.0\",\"publisher\":{\"api_key\":\"05dde50f1d1a384dd78767c55493e4bb\",\"name\":\"GitHub\"},\"entity\":{\"external_key\":\"github/PorteAperteSulWeb/pasw2015\",\"title\":\"PorteAperteSulWeb/pasw2015\",\"subtitle\":\"GitHub repository\",\"main_image_url\":\"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png\",\"avatar_image_url\":\"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png\",\"action\":{\"name\":\"Open in GitHub\",\"url\":\"https://github.com/PorteAperteSulWeb/pasw2015\"}},\"updates\":{\"snippets\":[{\"icon\":\"PERSON\",\"message\":\"@emitz in #201: Ho effettuato l'aggiornamento e si è verificato lo stesso tuo problema. Ho provato, come hai fatti tu, a rinominare la cartella ma anche a me è scomparso il sito e quindi ho rinominato nuovamente. \\r\\nTu sei poi riuscito a risolvere il problema? \"}],\"action\":{\"name\":\"View Issue\",\"url\":\"https://github.com/PorteAperteSulWeb/pasw2015/issues/201#issuecomment-314486707\"}}}\n\u003e—\n\u003eYou are receiving this because you commented.\n\u003eReply to this email directly,  view it on GitHub , or  mute the thread .\n"}],"action":{"name":"View Issue","url":"https://github.com/PorteAperteSulWeb/pasw2015/issues/201#issuecomment-314811385"}}}

**Comment by emitz** [comment]
Ciao. Io sul sito ho anche pasw2013 quindi da bacheca sono andata su aspetto temi e ho attivato pasw2013. Poi con filezilla ho modificato il nome della famosa cartella. Infine sono tornata nel sto in bacheca e ho riattivato pasw2015. Fammi sapere se sono stata chiara.  Ciao Emanuela

mercoledì 12 luglio 2017, 20:15 +0200 da roberbi  <notifications@github.com>:

**Comment by roberbi** [comment]
Ciao Emanuela
Ti ringrazio per l'attenzione che mi hai dato. Ho risolto il problema
attivando un altro tema e poi dopo aver rinominato la cartella riattivato
pasw15. Ringrazio te e la persona che ti ha dato il suggerimento. La cosa
strana è che l'aggiornamento sul sito che ho per fare le prove, non ha dato
questo problema. Mah misteri dell'informatica!

Se ti va di vedere il mio lavoro sul sito di istituto ecco il link
https://www.iisprever.gov.it
Se vuoi vedere il network multisito che ho creato per le attività
didattiche il link è https://www.iisprever.gov.it/comprever

Ciao e ancora grazie
Roberto

Il giorno 13 luglio 2017 09:25, emitz <notifications@github.com> ha scritto:

**Comment by emitz** [comment]
Ciao Roberto, sono contenta che anche tu abbia risolto il problema. Ho dato
una sbirciatina al tuo sito e...wow bravi! Sono state adottate belle
soluzione nella homepage....magari ti chiederò qualche consiglio😊
Buona giornata
Emanuela

Il giorno 13 luglio 2017 13:57, roberbi <notifications@github.com> ha
scritto:

**Comment by roberbi** [comment]
CiaoChiedi pure. Grazie ancoraRoberto.


Inviato da smartphone Samsung Galaxy.
-------- Messaggio originale --------Da: emitz <notifications@github.com> Data: 13/07/17  15:31  (GMT+01:00) A: PorteAperteSulWeb/pasw2015 <pasw2015@noreply.github.com> Cc: roberbi <rbtbnc@gmail.com>, Author <author@noreply.github.com> Oggetto: Re: [PorteAperteSulWeb/pasw2015] Riscrivere nome directory (#201) 
Ciao Roberto, sono contenta che anche tu abbia risolto il problema. Ho dato

una sbirciatina al tuo sito e...wow bravi! Sono state adottate belle

soluzione nella homepage....magari ti chiederò qualche consiglio😊

Buona giornata

Emanuela



Il giorno 13 luglio 2017 13:57, roberbi <notifications@github.com> ha

scritto:

**Comment by cghellere** [comment]
Vista la risoluzione del problema chiudo l'issue
