### ISSUE TITLE
problemi aggiornamento pasw2015 versione 1.7

### ISSUE THREAD

**Issue by emitz** [PorteAperteSulWeb/pasw2015#203]
Buongiorno,
con l'aggiornamento alla versione 1.7 del tema pasw2015 mi succedono 2 cose che non riesco a modificare:
1) nella testata e nel piè di pagina non compare più il simbolo della repubblica italiana e non capisco come fare per inserirlo nuovamente;
2) in bacheca mi appare sempre la scritta "Pasw2015 è installato nella directory "PorteAperteSulWeb-pasw2015-58014d6". Per un corretto funzionamento è necessario cambiare il nome della cartella in "pasw2015".
Qualcuno mi può aiutare?
Grazie

**Comment by maupao** [comment]
Il giorno Tue, 11 Jul 2017 09:36:22 +0000 (UTC)
emitz <notifications@github.com> ha scritto:

> con l'aggiornamento alla versione 1.7 del tema pasw2015 mi succedono
> 2 cose che non riesco a modificare: 1) nella testata e nel piè di
> pagina non compare più il simbolo della repubblica italiana e non
> capisco come fare per inserirlo nuovamente; 2) in bacheca mi appare
> sempre la scritta "Pasw2015 è installato nella directory
> "PorteAperteSulWeb-pasw2015-58014d6". Per un corretto funzionamento è
> necessario cambiare il nome della cartella in "pasw2015". Qualcuno mi
> può aiutare?
Credo che tutto dipenda dalla diversa denominazione della cartella nel
server. Devi accedere via ftp e cambiare il nome come indicato sopra,
da PorteApertesulWeb... a pasw2015 e vedi se si sistema anche il
discorso dello stemma
Paolo

**Comment by emitz** [comment]
Gentile Paolo, innanzitutto grazie del tuo aiuto però, purtroppo, io ho provato a seguire il tuo suggerimento ma cambiando il nome della cartella (ho usato filezilla) è scomparso il sito. Al suo posto una scritta che diceva che la directory " PorteAperteSulWeb-pasw2015-58014d6" non esisteva più. Ho quindi provveduto a rinominare nuovamente la cartella. Ho forse sbagliato qualcosa?

Emanuela

martedì 11 luglio 2017, 12:12 +0200 da Paolo Mauri  <notifications@github.com>:

**Comment by cghellere** [comment]
In questi casi non so se convenga cambiare tema, rinominare la cartella pasw2015 e poi riattivare il tema pasw. Non ricordo se con questa operazione necessita riconfigurare le sidebar.

Comportamento anomalo di github per questo update :-(

**Comment by emitz** [comment]
Ha funzionato, grazie infinite Ghellere. Sono riapparsi anche gli stemmi!!!!
