### ISSUE TITLE
Problema Barra laterale DX

### ISSUE THREAD

**Issue by ambrix** [PorteAperteSulWeb/pasw2015#212]
Salve,
ho installato un plugin che utilizzo su più temi wordpress (Social Media Widget by Acurax), tuttavia quando lo voglio visualizzare nella barra laterale dx, le singole icone mi appaiono in fila verticale. Ho provato a modificare la #rightsidebar da editor child,, ma non ha funzionato. Come posso fare a visualizzarle in fila orizzontale?  Allego link di esempio: 
http://www.isisstaddeodasessa.gov.it/orario-lezioni/
Grazie

**Comment by cghellere** [comment]
Ciao dovresti provare con un css simile a questo

.acx-smw-social-icon-desc li.widget {
	display: inline !important;
}

**Comment by ambrix** [comment]
Ciao, 
ho risolto in questo modo:

.acx_smw_float_fix {
display: inline-flex !important;
}

grazie 
saluti
