### ISSUE TITLE
Pasw2015 e PHP7.2

### ISSUE THREAD

**Issue by gcielo** [PorteAperteSulWeb/pasw2015#235]
Ho provato ad utilizzare la versione beta di pasw2015 per PHP 7.xx ma ottengo i seguenti problemi:
FILE: /web/htdocs/www.comprensivounochieti.gov.it/home/wp-content/themes/pasw2015/github/vendor/parse-readme.php
----------------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
----------------------------------------------------------------------------------------------------------------
 5 | WARNING | Use of deprecated PHP4 style class constructor is not supported since PHP 7.
----------------------------------------------------------------------------------------------------------------

FILE: /web/htdocs/www.comprensivounochieti.gov.it/home/wp-content/themes/pasw2015/github/vendor/Parsedown.php
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 894 | ERROR | Indirect access to variables, properties and methods will be evaluated strictly in left-to-right order since PHP 7.0. Use curly braces to remove ambiguity.
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------

FILE: /web/htdocs/www.comprensivounochieti.gov.it/home/wp-content/themes/pasw2015/include/impostazioni-pasw2015-saver.php
-----------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 4 ERRORS AFFECTING 1 LINE
-----------------------------------------------------------------------------------------------------------------------------------------------------
 5 | ERROR | Extension 'mcrypt' is deprecated since PHP 7.1 and removed since PHP 7.2; Use openssl (preferred) or pecl/mcrypt once available instead
 5 | ERROR | Function mcrypt_encrypt() is deprecated since PHP 7.1 and removed since PHP 7.2; Use OpenSSL instead
 5 | ERROR | The constant "MCRYPT_RIJNDAEL_256" is deprecated since PHP 7.1 and removed since PHP 7.2
 5 | ERROR | The constant "MCRYPT_MODE_CBC" is deprecated since PHP 7.1 and removed since PHP 7.2
-----------------------------------------------------------------------------------------------------------------------------------------------------

FILE: /web/htdocs/www.comprensivounochieti.gov.it/home/wp-content/themes/pasw2015/include/GAAPIOLD/gacounter.php
------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 4 ERRORS AFFECTING 1 LINE
------------------------------------------------------------------------------------------------------------------------------------------------------
 27 | ERROR | Extension 'mcrypt' is deprecated since PHP 7.1 and removed since PHP 7.2; Use openssl (preferred) or pecl/mcrypt once available instead
 27 | ERROR | Function mcrypt_decrypt() is deprecated since PHP 7.1 and removed since PHP 7.2; Use OpenSSL instead
 27 | ERROR | The constant "MCRYPT_RIJNDAEL_256" is deprecated since PHP 7.1 and removed since PHP 7.2
 27 | ERROR | The constant "MCRYPT_MODE_CBC" is deprecated since PHP 7.1 and removed since PHP 7.2
------------------------------------------------------------------------------------------------------------------------------------------------------

FILE: /web/htdocs/www.comprensivounochieti.gov.it/home/wp-content/themes/pasw2015/include/moduli/pasw2015-multiple-sidebars.php
-------------------------------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
-------------------------------------------------------------------------------------------------------------------------------
 39 | WARNING | Use of deprecated PHP4 style class constructor is not supported since PHP 7.
-------------------------------------------------------------------------------------------------------------------------------

**Comment by kowalski215** [comment]
Proverei a vedere se funziona il PHP 7.0.
Non è Necessario (almeno non in termini assoluti) aggiornare all'ultima versione di PHP 7.x

**Comment by gcielo** [comment]
Non va nemmeno con il PHP7.0

Il mar 3 set 2019, 20:58 kowalski215 <notifications@github.com> ha scritto:

**Comment by kowalski215** [comment]
Non scompaiono nemmeno gli **ultimi** errori con il php 7.0?
Il primo si dovrebbe risolvere facilmente se si presenta..
