### ISSUE TITLE
Un errore di E_ERROR è stato causato nella linea 894 del file /web/htdocs/www.ctslaspezia.eu/home/wp-content/themes/PorteAperteSulWeb-pasw2015-d863253/github/vendor/Parsedown.php.

### ISSUE THREAD

**Issue by Daniela20-byte** [PorteAperteSulWeb/pasw2015#247]
Come posso fare per risolvere questi errori? HELP!
WordPress, a partire dalla versione 5.2, ha una funzionalità integrata che rileva quando un plugin o un tema provoca un errore irreversibile sul tuo sito e ti avvisa con questa email automatica.

In questo caso, WordPress ha incontrato un errore con il tuo tema, PASW 2015.

Per prima cosa, vai al tuo sito web (http://www.ctslaspezia.eu/) e controlla se ci sono problemi visibili. Successivamente, vai nella pagina in cui è stato rilevato l'errore (http://www.ctslaspezia.eu/wp-admin/) e verifica se c'è qualche problema visibile.

Contatta il tuo host per richiedere assistenza per una investigazione più approfondita di questo problema.

Se il tuo sito appare danneggiato e non puoi accedere normalmente alla tua bacheca, WordPress ora ha una speciale "modalità di ripristino". Ciò ti consente di accedere in modo sicuro alla tua bacheca per controllare cosa non va.

http://www.ctslaspezia.eu/wp-login.php?action=enter_recovery_mode&rm_token=4LjamXMBYr0XRYnzJg8Ywy&rm_key=WVM9FabG02HaDTPzDmonn7

Per mantenere il tuo sito sicuro, questo link scadrà tra 1 giorno. Non preoccuparti di questo: ti verrà inviato un nuovo link se l'errore si ripresenta dopo la scadenza.

Se cerchi aiuto per questo problema, ti potrebbero essere chieste alcune delle seguenti informazioni:
Versione di WordPress 5.6
Tema corrente: PASW 2015 (versione 1.6.7)
Plugin corrente:  (versione )
Versione PHP 7.2.33

Dettagli dell'errore
====================
Un errore di E_ERROR è stato causato nella linea 894 del file /web/htdocs/www.ctslaspezia.eu/home/wp-content/themes/PorteAperteSulWeb-pasw2015-d863253/github/vendor/Parsedown.php. Messaggio di errore: Uncaught Error: Function name must be a string in /web/htdocs/www.ctslaspezia.eu/home/wp-content/themes/PorteAperteSulWeb-pasw2015-d863253/github/vendor/Parsedown.php:894
Stack trace:
#0 /web/htdocs/www.ctslaspezia.eu/home/wp-content/themes/PorteAperteSulWeb-pasw2015-d863253/github/vendor/Parsedown.php(931): Parsedown->element(Array)
#1 /web/htdocs/www.ctslaspezia.eu/home/wp-content/themes/PorteAperteSulWeb-pasw2015-d863253/github/vendor/Parsedown.php(257): Parsedown->elements(Array)
#2 /web/htdocs/www.ctslaspezia.eu/home/wp-content/themes/PorteAperteSulWeb-pasw2015-d863253/github/vendor/Parsedown.php(48): Parsedown->lines(Array)
#3 /web/htdocs/www.ctslaspezia.eu/home/wp-content/themes/PorteAperteSulWeb-pasw2015-d863253/github/src/GitHub_Updater/GitHub_API.php(128): Parsedown->text('Per la lista co...')
#4 /web/htdocs/www.ctslaspezia.eu/home/wp-content/themes/PorteAperteSulWeb-pasw2015-d863253/github/src/GitHub_Updater/Theme.php(82): Fragen\GitHub_Updater\GitHub_API->get_remote_changes('CHANGELOG.md')
#5 /web

**Comment by milesimarco** [comment]
Daniela buonasera,
provi a cambiare la directory del tema in wp-content/themes/**pasw2015**.

Se il problema persiste, può installare il plugin "Github Updater" separatamente.

A disposizione,
Marco Milesi

**Comment by Daniela20-byte** [comment]
Buonasera Marco,
in pratica dovrei andare via FTP fare cosa? Avrei bisogno di una spiegazione passo passo.
Grazie per l'attenzione ! HELP!

**Comment by milesimarco** [comment]
Si confermo, via ftp va rinominata la cartella del tema. Si trova in wp-content/themes e va rinominata da PorteAperteSulWeb-pasw2015-d863253 a "pasw2015"

**Comment by Daniela20-byte** [comment]
Buonasera,
in wp-content/themes trovo queste cartelle: pasw2015 e PorteAperteSulWeb-pasw2015-d863253
Come devo fare per correggere l'errore?

Ringrazio per l'attenzione e saluto

**Comment by maupao** [comment]
Ciao Daniela, credo che dovresti eliminare la cartella pasw2015 e rinominare PorteAperteSulWeb-pasw2015-d863253 in pasw2015.

**Comment by Daniela20-byte** [comment]
Un grandissimo grazie a Marco Milesi per tutti i consigli e a Paolo Mauri per l'aiuto!!!
Buone feste!
