### ISSUE TITLE
Il plugin GitHub Updater deve essere installato. Ma non lo trova

### ISSUE THREAD

**Issue by IsabellaTarini** [PorteAperteSulWeb/pasw2015#252]
Salve,
sono poco esperta e gestisco da poco un sito scolastico creato (non da me) con WordPress.
Il tema istallato è "Pasw2015 Child", la versione di WordPress è 5.8.1 (ho fatto un aggiornamento alla versione più recente pochi giorni fa)

La bacheca dà il seguente messaggio di errore:
"Per un corretto funzionamento di PASW 2015 il plugin GitHub Updater deve essere installato. Install Now »"
tuttavia seguendo il link "Install Now" dà la risposta "Plugin download failed", e anche cercandolo a mano tra i plugin non risulta disponibile.

Il sito sembra funzionare in tutto e per tutto, ma sono preoccupata: il tema Pasw 2015 potrebbe smettere di funzionare?

Grazie!

**Comment by amelillo** [comment]
Segnalo lo stesso identico errore.
Dalla pagina dei plugin è possibile trovare Git Updater, disabilitato, che può essere attivato manualmente.
Tuttavia, anche dopo l'attivazione, l'update fallisce.

**Comment by mldeluca** [comment]
Sto riscontrando lo stesso problema, qualcuno ha capito cosa succede?

**Comment by milesimarco** [comment]
Buonasera,
l'anomalia, per vecchie installazioni, dovrebbe risolversi variando il nome della cartella wp-content/plugins/github-updater in wp-content/plugins/git-updater.

Sarà rilasciato anche un fix di questo problema, che riguarda il componente che consente di aggiornare in automatico il tema ma non inficia sul funzionamento del portale!

A presto,
Marco Milesi

**Comment by amelillo** [comment]
Grazie del supporto.
Purtroppo immagino che come me molti colleghi che usano PASW2015 hanno accesso solo al pannello di amministrazione Wordpress ma non all'ftp dell'hosting, per cui agire manualmente sulle cartelle di Wordpress è all'atto pratico impossibile.
Grazie ancora e buon lavoro (^_^)
am

**Comment by maupao** [comment]
Ho risolto facendo così senza accedere all'ftp dell'hosting:
* ho rimosso il plugin github-updater;
* ho scaricato [dal sito](https://git-updater.com/wp-content/uploads/2021/10/git-updater-10.6.6.zip) il plugin git-updater
* ho installato il nuovo plugin git-updater caricando il pacchetto zip
Una volta attivato è comparsa la notifica di aggiornamento del tema e ho potuto portare il tema alla versione 2.2.1

**Comment by amelillo** [comment]
Tecnicamente funziona, ma purtroppo il plugin ha cambiato mome (da GitHub Updater a Git Updater) per cui anche se la funzionalità è la stessa e quindi gli aggiornamenti vengono fatti, non ci sbarazziamo del warning su GitHub Updater.
Non che sia un problema, ma il messaggio resta.
Grazie e ciao

**Comment by amelillo** [comment]
Ops, perdonatemi ma invece dopo una giornata (me ne sono appena accorto) e un logout/login è scomparso anche il warning.
Grazie ancora.

**Comment by maupao** [comment]
Il Mon, 29 Nov 2021 06:17:08 -0800
amelillo ***@***.***> scriveva:

> Ops, perdonatemi ma invece dopo una giornata (me ne sono appena
> accorto) e un logout/login è scomparso anche il warning. Grazie
> ancora.
> 

Infatti, prima di scrivere ho verificato e il warning era sparito.

-- 
Paolo Mauri
Linux User #462825
irc maupao
twitter @mauri_paolo
www.paolomauri.it
mastodon ***@***.***
matrix @maupao:matrix.org

un sistema libero per la scuola
http://wiki.scuola.linux.it

Esci dall'illegalità: utilizza LibreOffice.org: 
http://www.libreoffice.org/download
http://linguistico.sourceforge.net/wiki/doku.php?id=usaooo
http://linguistico.sourceforge.net/pages/traduzioni/ms_illegal.html

**Comment by maupao** [comment]
@milesimarco penso che questo si possa chiudere, che ne pensi?
