### ISSUE TITLE
Aggiornamento tema pasw2015 versione 2.3.1.

### ISSUE THREAD

**Issue by filippo-c** [PorteAperteSulWeb/pasw2015#258]
Buonasera, 
nella bacheca di wp esce l'avviso di aggiornare il tema, dopo averlo aggiornato compare di nuovo l'avviso di aggiornare il tema (Pasw2015). Grazie a chiunque possa aiutarmi.
![pasw2015](https://user-images.githubusercontent.com/65071977/197294207-19f16a55-cfdf-4ba8-814b-a60fe203cad1.png)

**Comment by Omeromuscio** [comment]
buongiorno 
io uso la ver 2.2 e non trovo la possibilità di aggiornamenti ( per arrivare alla 2.3.1 che risolve il problema dei font di google
come doveri fare ( nel mio caso non compare l'opzione per aggiornare ma ho la ver 2.2)
grazie Alberto

**Comment by filippo-c** [comment]
Grazie, non capisco il problema, continuo a cliccare su aggiorna, sembra andare a buon fine, appena aggiorno la pagina ricompare il tema da aggiornare. Per caso c'è uno sviluppatore del tema che ci può aiutare!
![Annotazione 2022-11-07 214321](https://user-images.githubusercontent.com/65071977/200411563-aa3456ee-1c0a-43f0-a8cf-f537e679cda1.png)

**Comment by milesimarco** [comment]
Buongiorno a tutti,
potete gentilmente confermarmi se l'anomalia persiste con l'ultima release?

Grazie,
M.

**Comment by Omeromuscio** [comment]
Buongiorno  Marco per me è ok

Il Gio 10 Nov 2022, 12:16 Marco Milesi ***@***.***> ha
scritto:

**Comment by filippo-c** [comment]
Buongiorno Marco, ho aspettato a rispondere perché non mi aggiornava i
contenuti nei dispositivi mobili, forse dovuto all' installazione di un
plugin. Adesso tutto ok, se ci sono eventuali problematiche lo segnalerò.
Cordialmente Filippo

Il Gio 10 Nov 2022, 12:19 Omeromuscio ***@***.***> ha scritto:

**Comment by maupao** [comment]
Confermo, anche da me tutto ok.

**Comment by milesimarco** [comment]
Grazie per il feedback, ciao!
