### ISSUE TITLE
Widgets spariti

### ISSUE THREAD

**Issue by Fuvola** [PorteAperteSulWeb/pasw2015#260]
Ciao a tutti, mi sono spariti i widgets del template , cioè quelli che di norma appaiono nella modalità "personalizza", mentre li ritrovo tutti tra i widgets di WP. Allego uno screenshot per essere più chiaro. Qualcuno sa darmi una risposta? come posso ripristinare le fasce che sono sparite nella home? Grazie mille per l'aiuto
![screen errore](https://user-images.githubusercontent.com/84680502/201154595-995482c0-bcb7-4f1a-91b5-d7b9a23326df.png)

**Comment by maupao** [comment]
Prova ad installare il plugin [Classic Widget](https://wordpress.org/plugins/classic-widgets/) e vedi che succede.

**Comment by Fuvola** [comment]
Grazie mille! purtroppo non succede nulla, se non che si passa alla vecchia visualizzazione dei widgets (senza blocchi, per intenderci). Nei widgets di WP io ho tutto a posto, compare tutto come impostato.
E' stata fatta qualche manovra sbagliata dalla segreteria (hanno rinominato la Home e quindi è sparito tutto tranne header e footer) e ho ripristinato in seguito la Home. Però non riesco a ripristinare le aree widget HOME e SOTTOHOME. L'unico posto in cui vedo questo errore è in "Personalizza", come vedi nella foto sopra.

**Comment by Fuvola** [comment]
Io penso di dover ripristinare le aree widget del tema, ma non so come fare.

**Comment by maupao** [comment]
Controlla la home che deve essere modello home page, trovi l'opzione nella parte a destra. Non sono al pc e non ricordo esattamente la dicitura

Il 11 novembre 2022 18:07:40 CET, Fuvola ***@***.***> ha scritto:
>Io penso di dover ripristinare le aree widget del tema, ma non so come fare. 
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/PorteAperteSulWeb/pasw2015/issues/260#issuecomment-1311955403
>You are receiving this because you commented.
>
>Message ID: ***@***.***>
-- 
Paolo Mauri
Inviato dal mio dispositivo Android con K-9 Mail. Perdonate la brevità.

**Comment by Fuvola** [comment]
GRAZIE!!!!!!!

è stata la prima mossa che fatto, ma non aveva dato risultati perché la Home era stata rinominata. Ora è tutto a posto. Ti devo un caffé

Grazie infinite, buon WE

**Comment by maupao** [comment]
Di niente, sono contento che tutto si sia risolto. Chiudo l'issue
