### ISSUE TITLE
Problema con google fonts

### ISSUE THREAD

**Issue by gbetta** [PorteAperteSulWeb/pasw2015#261]
Buongiorno, una società ha rilevato che il sito della scuola costruito con pasw2015, incorpora google font (google llc), dando 15 giorni di tempo alla scuola per mettersi in regola. In caso contrario, invierà segnalazione al garante per la privacy. 
Abbiamo eseguito delle procedure di controllo e in effetti risulta che il sito incorpora quanto descritto.
 Esiste una procedura per eliminare il problema?
Grazie.

**Comment by milesimarco** [comment]
Buongiorno @gbetta,
al seguente link può trovare l'ultima versione che include il fix del problema segnalato: https://github.com/PorteAperteSulWeb/pasw2015/releases

**Comment by gbetta** [comment]
Grazie mille.

Buone festività

Giovanni Bettanin

Il giorno mer 7 dic 2022 alle ore 02:05 Marco Milesi <
***@***.***> ha scritto:
