### ISSUE TITLE
Pagina statistiche

### ISSUE THREAD

**Issue by cghellere** [PorteAperteSulWeb/pasw2015#29]
Ciao Marco 
ho provato a creare la pagina delle statistiche seguendo la guida, creo la pagina e associo il template, quando vado in visualizzazione pagina la pagina non si carica completamente e compare questo ERRORE PASW2015@S01

Ho guardato su analytics e i dati di monitoraggio ci sono quindi i parametri inseriti sono corretti.

Grazie

Aggiornamento: 
Dopo aver aperto la pagina mi è arrivata questa email da google

```
Salve Christian,
```

Recentemente qualcuno ha utilizzato la tua password per tentare di accedere al tuo account Google XXXXXXXX XXXXXX  Questa persona stava utilizzando un'applicazione come un client di posta o un dispositivo mobile.

Abbiamo impedito il tentativo di accesso in quanto potrebbe essere opera di un malintezionato. Esamina i dettagli del tentativo di accesso:

```
mercoledì 3 dicembre 2014 13.32.55 UTC
```

Indirizzo IP: XXXXXXXXXXXX XXXXXXXXXXXXXX
Posizione: sconosciuta

Se non riconosci questo tentativo di accesso, è possibile che qualcun altro stia tentando di accedere al tuo account. Devi accedere al tuo account e reimpostare subito la password.

**Comment by Omeromuscio** [comment]
Buongiorno

ho utlizzato anch'io la guida per collegare analytis ad una pagina wordpress
ma nonostante il monitoraggio sia attivo nella pagina di wordpress non vedo niente
che protezioni dovrei abbassare in google per provare se il problema è simile a quello ci cghellere ?

grazie Alberto

**Comment by cghellere** [comment]
Ciao 
entra nel tuo account google -> vai in impostazioni -> scheda accesso -> Accesso per app meno sicure 


https://accounts.google.com/b/0/ManageAccount

**Comment by Omeromuscio** [comment]
grazie Chistian


nel mio caso l'accesso alle app meno sicure è già nello stato di attivato (
credo sia la condizione di defualt)
forse devo apsettare un pò proma che nella pagina dove ho attivato il
template di statistiche possa vedere il contenuto ?

ciao e grazie ancora Alberto

2015-03-18 13:29 GMT+01:00 Christian Ghellere <notifications@github.com>:

**Comment by Omeromuscio** [comment]
ciao Cristian

è poi partito

è successo come ha te mi è stato segnalato un comportamento sospetto sul
sito di google che mi ha fatto cambiare la password di accesso
dopo un pò sono riuscito a visulaizzare nela pagina con template acessi il
riepilogo di goggle analytisc

grazie ancora Alberto

Il giorno 18 marzo 2015 14:17, Bettini, Alberto <alberto@albertobettini.info
