### ISSUE TITLE
Elenco Categorie

### ISSUE THREAD

**Issue by Peste61** [PorteAperteSulWeb/pasw2015#47]
Nella creazione di una nuova pagina non è possibile associare la categoria perchè non c'è il pannello.
Saluti stefano

**Comment by milesimarco** [comment]
Devi attivare il modulo

Inviata dal mio Windows Phone
________________________________
Da: Peste61<mailto:notifications@github.com>
Inviato: ‎02/‎01/‎2015 23:50
A: PorteAperteSulWeb/pasw2015<mailto:pasw2015@noreply.github.com>
Oggetto: [pasw2015] Elenco Categorie (#47)

Nella creazione di una nuova pagina non è possibile associare la categoria perchè non c'è il pannello.
Saluti stefano

---
Reply to this email directly or view it on GitHub:
https://github.com/PorteAperteSulWeb/pasw2015/issues/47
