### ISSUE TITLE
Problema link

### ISSUE THREAD

**Issue by edoardotortora** [PorteAperteSulWeb/pasw2015#59]
Buongiorno,
Volevo segnalare il problema dei link in pannello amministrazione. Dopo aver installato wp 4.1 e pasw2015, nella barra principale del pannello amministratore non compare la scelta di inserimento dei link. Grazie Edoardo

**Comment by milesimarco** [comment]
E’ una scelta del team di WordPress. Per riattivare tale funzionalità bisogna installare il plugin “Link Manager”
https://wordpress.org/plugins/link-manager/

__
Marco Milesi
San Pellegrino Terme (BG) | www.marcomilesi.ml
tel. 377 136 4295

Le informazioni contenute in questo messaggio di posta elettronica sono confidenziali e sono da considerarsi strettamente riservate. 
Qualora Lei lo avesse ricevuto per errore La preghiamo di comunicarne la ricezione inviando una e-mail al mittente e di distruggerne il contenuto.


From: edoardotortora 
Sent: Saturday, January 17, 2015 6:50 AM
To: PorteAperteSulWeb/pasw2015 
Subject: [pasw2015] Problema link (#59)

Buongiorno,
Volevo segnalare il problema dei link in pannello amministrazione. Dopo aver installato wp 4.1 e pasw2015, nella barra principale del pannello amministratore non compare la scelta di inserimento dei link. Grazie Edoardo
