### ISSUE TITLE
Errore colori primari(Menu)

### ISSUE THREAD

**Issue by maicol07** [PorteAperteSulWeb/pasw2015#60]
Ciao,
ho rilevato un errore durante la modifica dei colori primari (dei menu, il colore predefinito è il blu). Quando li cambio le scritte nei bottoni del menu spariscono (immagine) e si visualizzano solo quando passate sopra con il mouse o cliccate.
![errore_menu](https://cloud.githubusercontent.com/assets/9463142/5792774/c69844e4-9f29-11e4-8f0a-f9ff4e6a8250.png)

**Comment by maicol07** [comment]
Risposte?

**Comment by cghellere** [comment]
Ciao ho fatto una prova giusto ora, ho variato il colore principale e nell'anteprima spariscono ma nel sito online tutto OK.
Vedo che il colore del testo è verde come quello dello sfondo e quindi risulta normale che non si vedano, ora si deve capire se hai variato tu il colore del testo ? di default anche cambiando sfondo il colore del carattere è bianco

**Comment by milesimarco** [comment]
Il problema riguarda solo l'anteprima in quanto non prende tutti i parametri css (se ci fai caso anche l'ombreggiatura dietro il menù non cambia colore nell'anteprima). Il sito "frontend" invece, ovviamente, carica tutte le personalizzazioni.

Risolvere significherebbe caricare ulteriormente l'anteprima di Javascript, e non so quanto possa essere producente. Cosa ne pensate?
