### ISSUE TITLE
Errore di validazione e correzione file archive.php

### ISSUE THREAD

**Issue by ricboc** [PorteAperteSulWeb/pasw2015#61]
Se non ci sono contenuti in amministrazione trasparente, se provo a controllare la validazione mi segnala la presenza del seguente errore

Line 315, Column 110: No p element in scope but a p end tag seen.
"Spiacenti, ma non ci sono articoli per questa categoria."

Allora ho modificato la riga 44 nel file archive.php del tema password 2015 togliendo il tag 'p' di apertura e chiusura in cima e in fondo e l'errore non c'e' piu'

riccardo

**Comment by milesimarco** [comment]
Corretto. Se aggiorni alla versione /master puoi avere la modifica nel tuo sito... Grazie!!
