### ISSUE TITLE
Generazione file xml

### ISSUE THREAD

**Issue by pinozito** [PorteAperteSulWeb/pasw2015#62]
Dopo aver inserito i dati delle gare per la generazione del file xml per AVCP vengono evidenziati problemi del tipo
Error 1839: Element 'codiceFiscaleProp': [facet 'pattern'] The value '80048770822 ' is not accepted by the pattern '[0-9]{11,11}'. in /web/htdocs/www.icleonardosciascia.gov.it/home/wordpress/avcp/2014.xml on line 16 
Error 1824: Element 'codiceFiscaleProp': '80048770822 ' is not a valid value of the atomic type '{legge190_1_0}codiceFiscaleType'. in /web/htdocs/www.icleonardosciascia.gov.it/home/wordpress/avcp/2014.xml on line 16 
Error 1839: Element 'codiceFiscaleProp': [facet 'pattern'] The value '80048770822 ' is not accepted by the pattern '[0-9]{11,11}'. in /web/htdocs/www.icleonardosciascia.gov.it/home/wordpress/avcp/2014.xml on line 29 
Error 1824: Element 'codiceFiscaleProp': '80048770822 ' is not a valid value of the atomic type '{legge190_1_0}codiceFiscaleType'. in /web/htdocs/www.icleonardosciascia.gov.it/home/wordpress/avcp/2014.xml on line 29 
Premetto che i dati sono corretti in quanto inserisco o codice fiscale o partita IVA , a due giorni dalla scadenza come rimediare?
Grazie

**Comment by cghellere** [comment]
ci sono degli spazi dopo il codice fiscale e/o partita iva, prova a cancellarli.
Ricordo che questo spazio è per il template pasw2015 e non per i plugin di Marco, per i plugin tipo avcp c'è https://wpgov.it/supporto/

**Comment by pinozito** [comment]
Grazie Christian .
Sempre molto gentile e disponibile.
Il 28/gen/2015 18:21 "Christian" <notifications@github.com> ha scritto:
