### ISSUE TITLE
Modificare tema in locale

### ISSUE THREAD

**Issue by renato12** [PorteAperteSulWeb/pasw2015#63]
Ho personalizzato su remoto il tema pasw2015 (intestazione, widget, menu, footer ecc) in funzione delle esigenze della mia scuola di servizio. Adesso vorrei caricare le modifiche sulla versione del sito che ho in locale, ma non so quale o quali file selezionare. Ho provato a cercare il file in funzione di data ed orario di modifica, ma senza risultati. Qualcuno sa dirmi quali file contengono le modifiche? Grazie

**Comment by cghellere** [comment]
Puoi scaricare tutta la cartella pasw2015 dal tuo sito e ricaricarla in locale, in questo modo hai la situazione tema come quella del sito online.
Se vuoi trovare i file modificati scarica la cartella pasw2015 dal tuo sito e poi confrontala con quella che scarichi da github, ti rammento che ci sono sotware che fanno il confronto cartelle purtroppo io conosco solo software a pagamento es. beyond compare, ma penso che ci sia qualche cosa anche free

**Comment by renato12** [comment]
L'ho fatto, ma non funzionava. Magari ho sbagliato qualcosa.
comunque grazie, verificherò.

**Comment by cghellere** [comment]
Scusa per personalizzare cosa intendi? se intendi le voci di menù, i widget visibili ecc. quelle sono informazioni salvate nel DB e non nei file. Se quanto da te richiesto rientra nel caso descritto in precedenza ti consiglio di cercare sul web guide che spiegano come passare il sito da remoto a locale.

**Comment by cghellere** [comment]
Se rientri nel caso descritto nel post precedente ho trovato questo articolo http://ioliberamente.it/3162/spostare-wordpress-3-semplici-passi-senza-toccare-riga-codice/

**Comment by renato12** [comment]
Si, intendevo proprio voci di menù, widget ecc: ho apportato modifiche, annotato l'ora delle modifiche e ricercato ovunque un file con quella data e quell'ora, ma è stato inutile. Evidentemente sarà tutto salvato sul database.
Purtroppo, smanettando in locale, ho mandato in tilt xamp o non so che altro ed ho eliminato tutto. 
grazie mille comunque. eviterò d'impazzire alla ricerca inutile di file e farò un backup del db

**Comment by milesimarco** [comment]
Per fare prove in locale dai un'occhiata a Ampps: http://ampps.com/downloads
Io mi trovo bene :)

Comunque il trasferimento va fatto su tutto il sito, non a pezzi
A presto

**Comment by renato12** [comment]
Io uso xampp. 
Sto incontrando qualche difficoltà nell'importare in locale le modifiche fatte a menù, widget ecc in remoto. 
cghellere mi ha suggerito che le modifiche potessero trovarsi nel database, ma ho provato ad importare il db e la homepage non cambia. Ho provato prima importando il file xml esportato da wordpress ed è andata male (homepage resta identica a quella di base). Poi ho fatto un ulteriore tentativo con il file sql generato dal plugin wp_db_backup e qui è andato in tilt tutto per ben due volte.
