### ISSUE TITLE
Commenti su pagine non funzionano

### ISSUE THREAD

**Issue by renato12** [PorteAperteSulWeb/pasw2015#64]
Pare che i commenti siano attivabili sugli articoli ma non sulle pagine. Malgrado l'attivazione dei permessi, sulle pagine non riesco a visualizzare i commenti. Qualcuno potrebbe confermarmi se sbaglio qualcosa o c'è qualche problema nel nuovo tema?
Grazie
Renato

**Comment by cghellere** [comment]
Da quanto ho visto il codice di richiamo non è presente (se non mi è sfuggito), qui necessita l'intervento di @milesimarco

il codice di richiamo dovrebbe essere il seguente se vuoi personalizzare il tuo child.

// If comments are open or we have at least one comment, load up the comment template.
if ( comments_open() || get_comments_number() ) :
		comments_template();
endif; 

il codice va inserito nel file page.php prima di questo codice

?>
</div>
<?php
include(TEMPLATEPATH . '/rightsidebar.php');
get_footer();
?>

**Comment by renato12** [comment]
Ok. Provo ad attendere allora risposte da parte di @milesimarco; in alternativa tra qualche giorno provo a sperimentare il tuo suggerimento.
Grazie mille.

**Comment by renato12** [comment]
FANTASTICO! FUNZIONA!
Non ho saputo resistere ed ho provato subito.
Sei un grande. Grazie mille. :-)))))))

**Comment by milesimarco** [comment]
Ok, lo aggiungiamo. Ma in quanto a stile dei commenti come siamo messi?

**Comment by renato12** [comment]
Non capisco cosa intendi con stile dei commenti. Spero di rispondere alla tua domanda con quest'informazione: prima usavo un tema realizzato da una persona che aveva realizzato il sito della scuola in cui insegno. I commenti erano stati inseriti utilizzando quel tema e non pasw2015. Adesso sto cercando di creare un secondo sito con pasw2015
