### ISSUE TITLE
Codice "more" su pagine

### ISSUE THREAD

**Issue by renato12** [PorteAperteSulWeb/pasw2015#66]
Utilizzo il tema pasw2015.
All'interno della pagina "studenti", che mi permette di visualizzare tutti i comunicati ad essi indirizzati, trovo i codici di seguito copiati e incollati.

[destinatari tipo="page" utente="alunni" numero="" anno="" link="" ordine=""]
[destinatari tipo="post" utente="alunni" numero="50" anno="" link="Leggi tutte le novità per docenti" ordine="date"]

Tali codici permettono di elencare le pagine e gli articoli indirizzati agli studenti.
Ho aumentato il numero dei post da 5 a 50 per aumentare il numero di quelli visualizzabili.
Esiste un codice che mi permetta in automatico di dare la possibilità di visualizzare i post più vecchi (in questo caso oltre il cinquantesimo) e che si comporti un po' come "more"?
Grazie
renato

**Comment by cghellere** [comment]
Ciao 
il codice riportato era di una prima versione, ora l'opzione link puo' assumenere valore si/no.
Il valore si abilita un link all'archivio con suddivizione per pagine, prova a vedere se ti puo' tornare utile.

[destinatari tipo="post" utente="alunni" numero="50" anno="" link="si" ordine="date"]

**Comment by renato12** [comment]
grazie mille. utilissimo
ciao
