### ISSUE TITLE
Problema con importatore xml - spostamento voce "log in"

### ISSUE THREAD

**Issue by renato12** [PorteAperteSulWeb/pasw2015#78]
Credo che qualcosa non vada tra il tema ed il plugin d’importazione dei file xml.
Dopo aver duplicato il sito mediante database, ne ho aggiornato articoli e pagine importando un file xml. Ad importazione avvenuta, le voci di menu precedentemente esistenti sono risultate raddoppiate. Ho verificato importando nuovamente e le voci risultano triplicate.

Vorrei spostare la voce di log in/esci dalla barra principale a quella superiore, per darle minor risalto. Mi sembra di capire che bisognerebbe intervenire sulla testata, ma non capisco nulla di php. Se la cosa non è particolarmente problematica, potreste indicarmi come intervenire?

Grazie per il fantastico lavoro che avete fatto (questo tema è estremamente versatile) e per il supporto che date.

**Comment by cghellere** [comment]
<<< Dopo aver duplicato il sito mediante database, ne ho aggiornato articoli e pagine importando un file xml. Ad importazione avvenuta, le voci di menu precedentemente esistenti sono risultate raddoppiate. Ho verificato importando nuovamente e le voci risultano triplicate.  >>>

Questo non ha nulla a che vedere con il tema, lo stesso comportamento l'avevi anche con il tema di default di wp.
 
Per l'altra modifica come hai detto tu è da variare il file header.php, ho fatto una modifica veloce e ti riporto una foto non posso allegare file php.

tutto il codice è già presente nel file header.php originale lo devi solo spostare di posizione

![2015-03-07_11-55-27](https://cloud.githubusercontent.com/assets/8959593/6541156/c6a886c0-c4c1-11e4-8928-459a66622a9e.jpg)

**Comment by cghellere** [comment]
Risultato

![2015-03-07_12-06-51](https://cloud.githubusercontent.com/assets/8959593/6541169/878953c4-c4c2-11e4-96c0-c1e555edc0f8.jpg)

**Comment by renato12** [comment]
Grazie mille.
Per quanto riguarda l'importazione xml, non sapevo. Lavoravo su un sito realizzato da un esterno, il cui tema si comportava diversamente.
