### ISSUE TITLE
Visualizzazione immagini in evidenza

### ISSUE THREAD

**Issue by renato12** [PorteAperteSulWeb/pasw2015#80]
Non riesco a far visualizzare le immagini in evidenza.
Le immagini risultano impostate, ma non vengono visualizzate. Non capisco dove sia l'errore. C'è qualche impostazione particolare da attivare?
Grazie

**Comment by cghellere** [comment]
Scusa non vengono visualizzate nel singolo articolo? nella pagina destinatari ? dove?

**Comment by renato12** [comment]
Scusami tu. Al momento ho provato sia con gli articoli che con la sidebar in homepage. 
Ho impostato un'immagine in evidenza negli articoli, ma non viene visualizzata nè sull'articolo che compare in sintesi in homepage e neppure sull'articolo completo. dopo che lo seleziono e ne chiedo l'apertura totale. 
Sto inoltre cercando di sostituire la voce "amministrazione trasparente" (pagina inserita in menu/sidebar) con la relativa icona, impostata come immagine in evidenza. Non so se agisco correttamente. Prima di utilizzare questo tema, inserivo una widget testuale con un'immagine ed il relativo link. Non so se adesso basta inserire un'immagine in evidenza per avere l'immagine sulla sidebar. Spero di essere stato chiaro e grazie in anticipo.

**Comment by renato12** [comment]
No scusami, mi correggo. Ho appena scoperto una cosa per me strana. Ti mando innanzitutto un link al sito della scuola, così mi spiego meglio.

http://www.scuoladeledda.it/

Ho inserito immagini in evidenza sia all'articolo "Mobilità A.S. 2015-2016 – Graduatorie interne d’Istituto" che alla pagina/voce di menù "Amministrazione trasparente".
Mobilità A.S. 2015-2016 – Graduatorie interne d’Istituto: se visualizzo l'articolo sulla homepage non visualizzo nulla, ma se visualizzo attraverso la categoria "Albo pretorio" presente in homepage sulla balla principale, l'immagine viene visualizzata.

**Comment by cghellere** [comment]
Ciao quale widget hai usato per fare le ultime notizie? se in quel widget non è prevista la visualizzazione dell'immagine è normale che sia così. 

Da albo invece vai alla categoria e quel template prevede la visualizzazione.

**Comment by renato12** [comment]
Per ultime notizie nessun widget: ho semplicemente settato in maniera tale che sulla homepage si vedessero le news.
In merito ai settaggi visualizzazioni ieri cercavo in rete qualcosa in  merito e letto che bisognava aggiungere una stringa al file functions.php. con l'istruzione add_theme_support.
in questo momento c'è l'istruzione 

add_theme_support('post-thumbnails');

Scusa l'ignoranza e cortesemente correggimi se sbaglio: se inserisco

add_theme_support( 'post-thumbnails', array( 'post',"page") );

consento la visualizzazione delle immagini su articoli e pagine?
sempre 1000 grazie per la disponibilità

**Comment by cghellere** [comment]
Scusami ma perchè hai fatto questo giro e modifiche quando si poteva usare le risorse del tema, potevi usare il widget pasw @categorie, dove puoi decidere quale categoria far visualizzare (es. Avvisi) far vedere o meno il riassunto e l'immagine.

**Comment by renato12** [comment]
non ricordo esattamente come, ma ho settato la homepage statica in maniera che si potessero vedere anche gli articoli appartenenti alla categoria avvisi.
scopro solo adesso la funzionalità (fantastica) di questo widget di cui mi parli. Esiste una sorta di manuale che elenchi tutta questa roba? Ci sono parecchi widget delle quali non conosco funzionalità.
Non capisco però come potrei inserire il widget pasw @categorie all'interno della homepage.

**Comment by renato12** [comment]
"Per l'immagine di amministrazione, fai come prima con l'uso del widget testo."

Ho provato a seguire il tuo consiglio, ma il validatore w3c mi restituisce una serie di errori in merito all'uso di alcuni parametri obsoleti. Forse è meglio lasciare tutto come si trova.

**Comment by renato12** [comment]
ho appena realizzato di aver già fatto proprio quanto suggerisci: avevo letto di questo windget sulle wiki.

**Comment by cghellere** [comment]
Se utilizzi già il widget vai nelle impostazioni e attiva la voce visualizza immagine in evidenza ed il gioco è fatto.

**Comment by renato12** [comment]
:-) mi era sfuggito. Grazie mille.
Ieri ho scoperto che sulle wiki c'erano tante informazioni interessanti che mi erano sfuggite anch'esse.
PS ho provato a risolvere il problema come mi suggerivi
"Per l'immagine di amministrazione, fai come prima con l'uso del widget testo." ma il validatore w3c mi restituisce parecchi errori.
 
questa una sintesi di ciò che inserisco

<p align="center">
<a href=" xxxxxxxxxxx" target=""> 
<img src="xxxxxxxxx/trasparenza-amministrativa.jpg" alt="" width="160"  height="50" border="0"  /></p> </a><p align="center">

e questo l'elenco degli errori. forse è meglio lasciare le cose come stanno....

Error Line 340, Column 88: The align attribute on the p element is obsolete. Use CSS instead.
…ext-7" class="widget widget_text">			<div class="textwidget"><p align="center">
✉
Error Line 341, Column 63: Bad value for attribute target on element a: Browsing context name must be at least one character long.
<a href=" http://www.scuoladeledda.it/?page_id=6826" target=""> 
Syntax of browsing context name or keyword:
A browsing context name or keyword is either any string that does not start with an underscore (_) or a string that case-insensitively matches one of: _blank, _self, _parent, or _top.
Warning Line 342, Column 143: The border attribute is obsolete. Consider specifying img { border: 0; } in CSS instead.
….jpg" alt="" width="160"  height="50" border="0"  /></p> </a><p align="center">
✉
Error Line 342, Column 147: End tag p seen, but there were open elements.
….jpg" alt="" width="160"  height="50" border="0"  /></p> </a><p align="center">
✉
Error Line 341, Column 63: Unclosed element a.
<a href=" http://www.scuoladeledda.it/?page_id=6826" target=""> 
✉
Error Line 342, Column 148: Bad value for attribute target on element a: Browsing context name must be at least one character long.
….jpg" alt="" width="160"  height="50" border="0"  /></p> </a><p align="center">
Syntax of browsing context name or keyword:
A browsing context name or keyword is either any string that does not start with an underscore (_) or a string that case-insensitively matches one of: _blank, _self, _parent, or _top.
Error Line 342, Column 170: The align attribute on the p element is obsolete. Use CSS instead.
….jpg" alt="" width="160"  height="50" border="0"  /></p> </a><p align="center">
✉
Error Line 343, Column 22: The font element is obsolete. Use CSS instead.
<font color="#FFFFFF">Amministrazione trasparente</font></div>

**Comment by cghellere** [comment]
io uso un codice simile a questo e viene validato
<a href="http://url.pippo" target="_blank" title="link esterno ammministrazione trasparente"><img src="http://url_images" alt="immagine amministrazione trasparente"  width="180"/></a>

**Comment by renato12** [comment]
proverò con questo.
grazie
