### ISSUE TITLE
Plugin Prenotazioni...

### ISSUE THREAD

**Issue by matronel** [PorteAperteSulWeb/pasw2015#82]
Qualcuno mi sa dire come farlo funzionare? Ho inserito gli spazi regolato i parametri ma non capisco come farlo vedere sul mio sito web. 
Questo è il link del plugin https://wordpress.org/plugins/prenotazioni/

**Comment by milesimarco** [comment]
Ciao @matronel 
questo spazio è utilizzato per chiedere/ricevere aiuto specifico sul tema grafico pasw2015.

Per informazioni sul plugin ti consiglio di chiedere nel gruppo Facebook "Siti Scolastici". in un canale di supporto Porte Aperte sul Web (mailing list di yahoo, scuolacooperativa,...) o direttamente allo sviluppatore Ignazio Scimone.

A presto
MM
